Import neccessary libraries

In [ ]:
import yaml
from pathlib import Path
import logging

import pandas as pd
import optuna
import mlflow
import mlflow.sklearn
import mlflow.lightgbm
import mlflow.xgboost

from sklearn.ensemble import RandomForestClassifier
from lightgbm import LGBMClassifier
from xgboost import XGBClassifier
from catboost import CatBoostClassifier

from sklearn.metrics import average_precision_score, log_loss, roc_auc_score
from sklearn.model_selection import StratifiedKFold, cross_val_predict
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score
)

# 1. THIẾT LẬP LOGGING (Dùng force=True để Jupyter không bị lỗi khi chạy lại cell nhiều lần)
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s",
    datefmt="%Y-%m-%d %H:%M:%S",
    force=True
)
logger = logging.getLogger(__name__)

# 2. ĐƯỜNG DẪN DỮ LIỆU
CLEANED_DATA_PATH = Path("../data/processed/cleaned_data.csv")
CONFIG_PATH = Path("../artifacts/models/best_model_config.yaml")
TARGET_COLUMN = "churn_status"
SPLIT_COLUMN = "data_split"
RANDOM_STATE = 42

In [7]:
mlflow.set_tracking_uri("http://127.0.0.1:5000/")
mlflow.set_experiment("Netflix_All_Models_Tuning")
# autolog can create many extra logs in notebook runs
# Keep it off for cleaner manual logging
# mlflow.sklearn.autolog()

overall_results = {}

2026/04/11 15:37:58 INFO mlflow.tracking.fluent: Experiment with name 'Netflix_All_Models_Tuning' does not exist. Creating a new experiment.

In [8]:
df = pd.read_csv(CLEANED_DATA_PATH)

In [9]:
# Basic validation
required_cols = {TARGET_COLUMN, SPLIT_COLUMN}
missing_cols = required_cols - set(df.columns)
if missing_cols:
    raise ValueError(f"Missing required columns: {missing_cols}")

if not set(df[SPLIT_COLUMN].unique()).issuperset({"train", "test"}):
    raise ValueError("Column 'data_split' must contain both 'train' and 'test' values.")

In [10]:
# =========================================
# Split data
# =========================================
train_set = df[df[SPLIT_COLUMN] == "train"].copy()
test_set = df[df[SPLIT_COLUMN] == "test"].copy()

if train_set.empty:
    raise ValueError("Train set is empty.")
if test_set.empty:
    raise ValueError("Test set is empty.")

X_train = train_set.drop(columns=[TARGET_COLUMN, SPLIT_COLUMN])
y_train = train_set[TARGET_COLUMN]

X_test = test_set.drop(columns=[TARGET_COLUMN, SPLIT_COLUMN])
y_test = test_set[TARGET_COLUMN]

# Cross-validation object for tuning on train set only
cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=RANDOM_STATE)

### BASELINE

In [50]:
from sklearn.linear_model import LogisticRegression

with mlflow.start_run(run_name="Baseline_LogisticRegression"):
    baseline_model = LogisticRegression(
        random_state=RANDOM_STATE,
        class_weight="balanced",
        max_iter=1000
    )
    baseline_model.fit(X_train, y_train)

    y_test_proba = baseline_model.predict_proba(X_test)[:, 1]
    y_test_pred = (y_test_proba >= 0.5).astype(int)

    test_metrics = {
        "test_pr_auc": float(average_precision_score(y_test, y_test_proba)),
        "test_roc_auc": float(roc_auc_score(y_test, y_test_proba)),
        "test_log_loss": float(log_loss(y_test, y_test_proba)),
        "test_accuracy": float(accuracy_score(y_test, y_test_pred)),
        "test_precision": float(precision_score(y_test, y_test_pred, zero_division=0)),
        "test_recall": float(recall_score(y_test, y_test_pred, zero_division=0)),
        "test_f1_score": float(f1_score(y_test, y_test_pred, zero_division=0)),
    }

    mlflow.log_params({
        "model_type": "LogisticRegression",
        "class_weight": "balanced",
        "max_iter": 1000,
        "random_state": RANDOM_STATE,
    })
    mlflow.log_metrics(test_metrics)

    overall_results["Baseline_LogisticRegression"] = {
        "model": baseline_model,
        "cv_pr_auc": None,
        "test_pr_auc": float(test_metrics["test_pr_auc"]),
        "params": {
            "class_weight": "balanced",
            "max_iter": 1000,
            "random_state": RANDOM_STATE,
        },
    }

🏃 View run Baseline_LogisticRegression at: http://127.0.0.1:5000/#/experiments/1/runs/53a23953afbc494fb563f8d5f6180942
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

### RANDOM FOREST

In [11]:
def objective_rf(trial):
    """
    Tune RandomForest using cross-validated PR-AUC on the training set only.
    This avoids test leakage during hyperparameter search.
    """
    params = {
        "n_estimators": trial.suggest_int("n_estimators", 100, 500),
        "max_depth": trial.suggest_int("max_depth", 5, 25),
        "min_samples_split": trial.suggest_int("min_samples_split", 2, 10),
        "min_samples_leaf": trial.suggest_int("min_samples_leaf", 1, 5),
        "criterion": trial.suggest_categorical("criterion", ["gini", "entropy"]),
        "random_state": RANDOM_STATE,
        "class_weight": "balanced",
        "n_jobs": -1,
    }

    model = RandomForestClassifier(**params)

    # Out-of-fold predicted probabilities on training data
    y_proba_oof = cross_val_predict(
        estimator=model,
        X=X_train,
        y=y_train,
        cv=cv,
        method="predict_proba",
        n_jobs=-1,
    )[:, 1]

    # Default classification threshold for reporting auxiliary metrics
    y_pred_oof = (y_proba_oof >= 0.5).astype(int)

    metrics = {
        "cv_pr_auc": float(average_precision_score(y_train, y_proba_oof)),
        "cv_roc_auc": float(roc_auc_score(y_train, y_proba_oof)),
        "cv_log_loss": float(log_loss(y_train, y_proba_oof)),
        "cv_accuracy": float(accuracy_score(y_train, y_pred_oof)),
        "cv_precision": float(precision_score(y_train, y_pred_oof, zero_division=0)),
        "cv_recall": float(recall_score(y_train, y_pred_oof, zero_division=0)),
        "cv_f1_score": float(f1_score(y_train, y_pred_oof, zero_division=0)),
    }

    # Log each Optuna trial as a nested MLflow run
    with mlflow.start_run(nested=True):
        mlflow.log_params(params)
        mlflow.log_metrics(metrics)

    return metrics["cv_pr_auc"]


with mlflow.start_run(run_name="RandomForest_PR_AUC_Optimization_CV"):
    logger.info("Starting RandomForest hyperparameter tuning with Stratified CV...")

    study_rf = optuna.create_study(direction="maximize")
    study_rf.optimize(objective_rf, n_trials=10)

    # Log best CV result
    mlflow.log_params(study_rf.best_params)
    mlflow.log_metric("best_cv_pr_auc", float(study_rf.best_value))

    # Train final RF model on full training set with best params
    best_rf = RandomForestClassifier(
        **study_rf.best_params,
        random_state=RANDOM_STATE,
        class_weight="balanced",
        n_jobs=-1,
    )
    best_rf.fit(X_train, y_train)

    # Final evaluation on untouched test set
    y_test_proba = best_rf.predict_proba(X_test)[:, 1]
    y_test_pred = (y_test_proba >= 0.5).astype(int)

    test_metrics = {
        "test_pr_auc": float(average_precision_score(y_test, y_test_proba)),
        "test_roc_auc": float(roc_auc_score(y_test, y_test_proba)),
        "test_log_loss": float(log_loss(y_test, y_test_proba)),
        "test_accuracy": float(accuracy_score(y_test, y_test_pred)),
        "test_precision": float(precision_score(y_test, y_test_pred, zero_division=0)),
        "test_recall": float(recall_score(y_test, y_test_pred, zero_division=0)),
        "test_f1_score": float(f1_score(y_test, y_test_pred, zero_division=0)),
    }

    mlflow.log_metrics(test_metrics)
    mlflow.sklearn.log_model(best_rf, name="best_rf_prauc_model")

    overall_results["RandomForest"] = {
        "model": best_rf,
        "cv_pr_auc": float(study_rf.best_value),
        "test_pr_auc": float(test_metrics["test_pr_auc"]),
        "params": study_rf.best_params,
    }

    print("-" * 40)
    print("RandomForest tuning completed!")
    print(f"Best CV PR-AUC: {study_rf.best_value:.4f}")
    print(f"Test PR-AUC: {test_metrics['test_pr_auc']:.4f}")
    print(f"Best Parameters: {study_rf.best_params}")

2026-04-11 15:41:14 [INFO] Starting RandomForest hyperparameter tuning with Stratified CV...
[I 2026-04-11 15:41:14,832] A new study created in memory with name: no-name-ffea8969-186f-4643-bcfe-1f45320de67b
[I 2026-04-11 15:41:24,690] Trial 0 finished with value: 0.23492892228870488 and parameters: {'n_estimators': 131, 'max_depth': 7, 'min_samples_split': 2, 'min_samples_leaf': 2, 'criterion': 'entropy'}. Best is trial 0 with value: 0.23492892228870488.

🏃 View run shivering-dove-897 at: http://127.0.0.1:5000/#/experiments/1/runs/2f2c5598c78b4653ac068db9f1154bc5
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

[I 2026-04-11 15:41:40,298] Trial 1 finished with value: 0.235396727594813 and parameters: {'n_estimators': 249, 'max_depth': 12, 'min_samples_split': 4, 'min_samples_leaf': 3, 'criterion': 'entropy'}. Best is trial 1 with value: 0.235396727594813.

🏃 View run trusting-panda-602 at: http://127.0.0.1:5000/#/experiments/1/runs/18d7a3118d114df1851c2d64b246fb0c
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

[I 2026-04-11 15:42:11,450] Trial 2 finished with value: 0.2350621529370029 and parameters: {'n_estimators': 490, 'max_depth': 20, 'min_samples_split': 2, 'min_samples_leaf': 3, 'criterion': 'gini'}. Best is trial 1 with value: 0.235396727594813.

🏃 View run skittish-owl-43 at: http://127.0.0.1:5000/#/experiments/1/runs/9f10330de3a44dcb8429720d1ba31f58
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

[I 2026-04-11 15:42:16,031] Trial 3 finished with value: 0.2383618528142179 and parameters: {'n_estimators': 105, 'max_depth': 11, 'min_samples_split': 8, 'min_samples_leaf': 2, 'criterion': 'gini'}. Best is trial 3 with value: 0.2383618528142179.

🏃 View run awesome-mare-969 at: http://127.0.0.1:5000/#/experiments/1/runs/a461356adbf74424ad439b69ed340c21
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

[I 2026-04-11 15:42:25,712] Trial 4 finished with value: 0.23538333682233248 and parameters: {'n_estimators': 194, 'max_depth': 17, 'min_samples_split': 7, 'min_samples_leaf': 3, 'criterion': 'gini'}. Best is trial 3 with value: 0.2383618528142179.

🏃 View run exultant-cat-873 at: http://127.0.0.1:5000/#/experiments/1/runs/6d3cc4c85d3b4cd3a54c01b7ef744f04
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

[I 2026-04-11 15:42:29,483] Trial 5 finished with value: 0.23492599414807605 and parameters: {'n_estimators': 112, 'max_depth': 8, 'min_samples_split': 8, 'min_samples_leaf': 5, 'criterion': 'entropy'}. Best is trial 3 with value: 0.2383618528142179.

🏃 View run agreeable-snake-158 at: http://127.0.0.1:5000/#/experiments/1/runs/6679c5a1b8924823b098173de5cc2089
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

[I 2026-04-11 15:42:49,092] Trial 6 finished with value: 0.23472515378267378 and parameters: {'n_estimators': 380, 'max_depth': 25, 'min_samples_split': 8, 'min_samples_leaf': 2, 'criterion': 'gini'}. Best is trial 3 with value: 0.2383618528142179.

🏃 View run likeable-penguin-816 at: http://127.0.0.1:5000/#/experiments/1/runs/929504ad8c564880ae07ba0c134e18f7
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

[I 2026-04-11 15:42:55,436] Trial 7 finished with value: 0.23876274902426903 and parameters: {'n_estimators': 207, 'max_depth': 9, 'min_samples_split': 7, 'min_samples_leaf': 5, 'criterion': 'entropy'}. Best is trial 7 with value: 0.23876274902426903.

🏃 View run enthused-moose-4 at: http://127.0.0.1:5000/#/experiments/1/runs/b95bea1ffe874dd18f7d3b15fe13bf70
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

[I 2026-04-11 15:43:03,911] Trial 8 finished with value: 0.2350838929793365 and parameters: {'n_estimators': 294, 'max_depth': 8, 'min_samples_split': 2, 'min_samples_leaf': 5, 'criterion': 'entropy'}. Best is trial 7 with value: 0.23876274902426903.

🏃 View run debonair-auk-500 at: http://127.0.0.1:5000/#/experiments/1/runs/d710267aaa4e488fa8f433a54719a1ab
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

[I 2026-04-11 15:43:17,247] Trial 9 finished with value: 0.2361526209721313 and parameters: {'n_estimators': 292, 'max_depth': 15, 'min_samples_split': 6, 'min_samples_leaf': 5, 'criterion': 'entropy'}. Best is trial 7 with value: 0.23876274902426903.

🏃 View run skittish-elk-151 at: http://127.0.0.1:5000/#/experiments/1/runs/d31377c440b94e89a544698859d1f3f5
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

2026/04/11 15:43:19 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html

----------------------------------------
RandomForest tuning completed!
Best CV PR-AUC: 0.2388
Test PR-AUC: 0.2405
Best Parameters: {'n_estimators': 207, 'max_depth': 9, 'min_samples_split': 7, 'min_samples_leaf': 5, 'criterion': 'entropy'}
🏃 View run RandomForest_PR_AUC_Optimization_CV at: http://127.0.0.1:5000/#/experiments/1/runs/0dc04227e2124669b277de436fcc0284
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

In [ ]:
# import matplotlib.pyplot as plt
# import pandas as pd

# # 1. Lấy độ quan trọng của các feature từ model tốt nhất
# importances = best_model.feature_importances_
# feature_names = X_train.columns

# # 2. Tạo DataFrame để dễ sắp xếp
# feature_importance_df = pd.DataFrame({'Feature': feature_names, 'Importance': importances})
# feature_importance_df = feature_importance_df.sort_values(by='Importance', ascending=False)

# # 3. In ra Top 5
# print("Top 5 Important Features:")
# print(feature_importance_df.head(5))

# # 4. Vẽ biểu đồ trực quan
# plt.figure(figsize=(10, 6))
# plt.barh(feature_importance_df['Feature'].head(5), feature_importance_df['Importance'].head(5), color='skyblue')
# plt.xlabel('Importance Score')
# plt.title('Top 5 Features causing potential Data Leakage')
# plt.gca().invert_yaxis()
# plt.show()

### XGBOOST

In [12]:
# =========================================
# XGBoost tuning with CV
# =========================================

# Class imbalance ratio for positive class weighting
ratio = float(y_train.value_counts()[0] / y_train.value_counts()[1])

def objective_xgb(trial):
    """
    Tune XGBoost using cross-validated PR-AUC on the training set only.
    This avoids test leakage during hyperparameter search.
    """
    params = {
        "n_estimators": trial.suggest_int("n_estimators", 100, 1000),
        "max_depth": trial.suggest_int("max_depth", 5, 15),
        "learning_rate": trial.suggest_float("learning_rate", 0.01, 0.3, log=True),
        "subsample": trial.suggest_float("subsample", 0.5, 1.0),
        "colsample_bytree": trial.suggest_float("colsample_bytree", 0.5, 1.0),
        "gamma": trial.suggest_float("gamma", 0.0, 5.0),
        "scale_pos_weight": trial.suggest_float("scale_pos_weight", 1.0, ratio * 1.5),
        "random_state": RANDOM_STATE,
        "eval_metric": "logloss",
        "n_jobs": -1,
    }

    model = XGBClassifier(**params)

    # Out-of-fold predicted probabilities on training data
    y_proba_oof = cross_val_predict(
        estimator=model,
        X=X_train,
        y=y_train,
        cv=cv,
        method="predict_proba",
        n_jobs=-1,
    )[:, 1]

    # Default classification threshold for reporting auxiliary metrics
    y_pred_oof = (y_proba_oof >= 0.5).astype(int)

    metrics = {
        "cv_pr_auc": float(average_precision_score(y_train, y_proba_oof)),
        "cv_roc_auc": float(roc_auc_score(y_train, y_proba_oof)),
        "cv_log_loss": float(log_loss(y_train, y_proba_oof)),
        "cv_accuracy": float(accuracy_score(y_train, y_pred_oof)),
        "cv_precision": float(precision_score(y_train, y_pred_oof, zero_division=0)),
        "cv_recall": float(recall_score(y_train, y_pred_oof, zero_division=0)),
        "cv_f1_score": float(f1_score(y_train, y_pred_oof, zero_division=0)),
    }

    # Log each Optuna trial as a nested MLflow run
    with mlflow.start_run(nested=True):
        mlflow.log_params(params)
        mlflow.log_metrics(metrics)

    return metrics["cv_pr_auc"]


with mlflow.start_run(run_name="XGBoost_PR_AUC_Optimization_CV"):
    logger.info("Starting XGBoost hyperparameter tuning with Stratified CV...")

    study_xgb = optuna.create_study(direction="maximize")
    study_xgb.optimize(objective_xgb, n_trials=50)

    # Log best CV result
    mlflow.log_params(study_xgb.best_params)
    mlflow.log_metric("best_cv_pr_auc", float(study_xgb.best_value))

    # Train final XGBoost model on full training set with best params
    best_xgb = XGBClassifier(
        **study_xgb.best_params,
        random_state=RANDOM_STATE,
        eval_metric="logloss",
        n_jobs=-1,
    )
    best_xgb.fit(X_train, y_train)

    # Final evaluation on untouched test set
    y_test_proba = best_xgb.predict_proba(X_test)[:, 1]
    y_test_pred = (y_test_proba >= 0.5).astype(int)

    test_metrics = {
        "test_pr_auc": float(average_precision_score(y_test, y_test_proba)),
        "test_roc_auc": float(roc_auc_score(y_test, y_test_proba)),
        "test_log_loss": float(log_loss(y_test, y_test_proba)),
        "test_accuracy": float(accuracy_score(y_test, y_test_pred)),
        "test_precision": float(precision_score(y_test, y_test_pred, zero_division=0)),
        "test_recall": float(recall_score(y_test, y_test_pred, zero_division=0)),
        "test_f1_score": float(f1_score(y_test, y_test_pred, zero_division=0)),
    }

    mlflow.log_metrics(test_metrics)
    mlflow.xgboost.log_model(best_xgb, name="best_xgb_prauc_model")

    overall_results["XGBoost"] = {
        "model": best_xgb,
        "cv_pr_auc": float(study_xgb.best_value),
        "test_pr_auc": float(test_metrics["test_pr_auc"]),
        "params": study_xgb.best_params,
    }

    print("-" * 40)
    print("XGBoost tuning completed!")
    print(f"Best CV PR-AUC: {study_xgb.best_value:.4f}")
    print(f"Test PR-AUC: {test_metrics['test_pr_auc']:.4f}")
    print(f"Best Parameters: {study_xgb.best_params}")

2026-04-11 15:52:41 [INFO] Starting XGBoost hyperparameter tuning with Stratified CV...
[I 2026-04-11 15:52:41,842] A new study created in memory with name: no-name-933a6a95-9ff4-41ca-a59b-c46fc3ce603e
[I 2026-04-11 15:52:58,222] Trial 0 finished with value: 0.2193665550393386 and parameters: {'n_estimators': 728, 'max_depth': 6, 'learning_rate': 0.04903112834352123, 'subsample': 0.6782584273320265, 'colsample_bytree': 0.982378206708919, 'gamma': 4.3206981309872186, 'scale_pos_weight': 4.769873010491647}. Best is trial 0 with value: 0.2193665550393386.

🏃 View run clumsy-goose-896 at: http://127.0.0.1:5000/#/experiments/1/runs/591619cae34e44fba7f9da5b98ed669c
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

[I 2026-04-11 15:53:26,119] Trial 1 finished with value: 0.2185396933424104 and parameters: {'n_estimators': 918, 'max_depth': 9, 'learning_rate': 0.03294265407620401, 'subsample': 0.561177852788644, 'colsample_bytree': 0.5498096547373519, 'gamma': 0.3292456536622107, 'scale_pos_weight': 6.003112670548729}. Best is trial 0 with value: 0.2193665550393386.

🏃 View run placid-fox-929 at: http://127.0.0.1:5000/#/experiments/1/runs/0f3f176f830c48ebae0e79323907bf8d
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

[I 2026-04-11 15:53:36,415] Trial 2 finished with value: 0.22280481932327512 and parameters: {'n_estimators': 377, 'max_depth': 6, 'learning_rate': 0.060874814794266506, 'subsample': 0.6078343869143698, 'colsample_bytree': 0.6842828032990894, 'gamma': 3.6029381149497675, 'scale_pos_weight': 6.99580111313232}. Best is trial 2 with value: 0.22280481932327512.

🏃 View run thundering-kit-196 at: http://127.0.0.1:5000/#/experiments/1/runs/4ba91799fd5c4d91a6fe5de33af8837d
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

[I 2026-04-11 15:53:47,807] Trial 3 finished with value: 0.22884870732728912 and parameters: {'n_estimators': 817, 'max_depth': 13, 'learning_rate': 0.037799352557632455, 'subsample': 0.8686099731209886, 'colsample_bytree': 0.902026779246923, 'gamma': 2.2258087371313993, 'scale_pos_weight': 2.4788812007857137}. Best is trial 3 with value: 0.22884870732728912.

🏃 View run receptive-asp-873 at: http://127.0.0.1:5000/#/experiments/1/runs/8599db849d44419c9d1ca3eed898aed8
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

[I 2026-04-11 15:53:57,262] Trial 4 finished with value: 0.219251079034517 and parameters: {'n_estimators': 839, 'max_depth': 7, 'learning_rate': 0.11923771946125111, 'subsample': 0.7267038395240077, 'colsample_bytree': 0.6105320178469318, 'gamma': 4.293058116285024, 'scale_pos_weight': 6.5316874577442645}. Best is trial 3 with value: 0.22884870732728912.

🏃 View run unruly-eel-162 at: http://127.0.0.1:5000/#/experiments/1/runs/71d838d3c93c496ea726003a9d9eceb1
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

[I 2026-04-11 15:54:03,532] Trial 5 finished with value: 0.2359067430452715 and parameters: {'n_estimators': 624, 'max_depth': 5, 'learning_rate': 0.0834704967657665, 'subsample': 0.8493543905121692, 'colsample_bytree': 0.7746959808025845, 'gamma': 3.20240433098353, 'scale_pos_weight': 1.6588653957683819}. Best is trial 5 with value: 0.2359067430452715.

🏃 View run bemused-crow-915 at: http://127.0.0.1:5000/#/experiments/1/runs/a2ab5cc377dd4d2682852002d5f1083e
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

[I 2026-04-11 15:54:06,570] Trial 6 finished with value: 0.22804695203499958 and parameters: {'n_estimators': 108, 'max_depth': 12, 'learning_rate': 0.08131293967111777, 'subsample': 0.8058579353436051, 'colsample_bytree': 0.9732793732205176, 'gamma': 3.928977046173791, 'scale_pos_weight': 2.6358071611806255}. Best is trial 5 with value: 0.2359067430452715.

🏃 View run luxuriant-robin-250 at: http://127.0.0.1:5000/#/experiments/1/runs/862c4ee5a4794ce6b24ccdfbf4e4ba6b
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

[I 2026-04-11 15:54:08,819] Trial 7 finished with value: 0.21679605471019353 and parameters: {'n_estimators': 117, 'max_depth': 10, 'learning_rate': 0.18878989136089072, 'subsample': 0.8798078459885287, 'colsample_bytree': 0.7759994293521846, 'gamma': 4.3835785650312955, 'scale_pos_weight': 6.791672130771381}. Best is trial 5 with value: 0.2359067430452715.

🏃 View run overjoyed-horse-566 at: http://127.0.0.1:5000/#/experiments/1/runs/f132153c5bbb4a19b3310d4fe4707536
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

[I 2026-04-11 15:54:15,776] Trial 8 finished with value: 0.22525643816952992 and parameters: {'n_estimators': 281, 'max_depth': 10, 'learning_rate': 0.04191536201884457, 'subsample': 0.6434252858424702, 'colsample_bytree': 0.8308938904309235, 'gamma': 3.2866129717401997, 'scale_pos_weight': 3.01647037103085}. Best is trial 5 with value: 0.2359067430452715.

🏃 View run invincible-crab-402 at: http://127.0.0.1:5000/#/experiments/1/runs/6af3703919ce4009b0b2ec04b81a9404
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

[I 2026-04-11 15:54:24,609] Trial 9 finished with value: 0.219438458249941 and parameters: {'n_estimators': 621, 'max_depth': 13, 'learning_rate': 0.14026871091409648, 'subsample': 0.8320641489277412, 'colsample_bytree': 0.9964032311170614, 'gamma': 1.7094337151834171, 'scale_pos_weight': 6.211220757609698}. Best is trial 5 with value: 0.2359067430452715.

🏃 View run chill-finch-397 at: http://127.0.0.1:5000/#/experiments/1/runs/96ac468d59b049bea7d92509a80c47fd
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

[I 2026-04-11 15:54:44,228] Trial 10 finished with value: 0.23091074641911635 and parameters: {'n_estimators': 471, 'max_depth': 15, 'learning_rate': 0.012322060977711135, 'subsample': 0.9787754316282922, 'colsample_bytree': 0.7044655340015411, 'gamma': 0.9500728943472214, 'scale_pos_weight': 1.155880238901192}. Best is trial 5 with value: 0.2359067430452715.

🏃 View run secretive-conch-474 at: http://127.0.0.1:5000/#/experiments/1/runs/41e6432a15d943a4bbdf00ff97b1709b
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

[I 2026-04-11 15:55:05,284] Trial 11 finished with value: 0.23027418249049436 and parameters: {'n_estimators': 499, 'max_depth': 15, 'learning_rate': 0.010241929438770015, 'subsample': 0.9851534356307354, 'colsample_bytree': 0.702773874512497, 'gamma': 1.1060388649573332, 'scale_pos_weight': 1.1399592284871953}. Best is trial 5 with value: 0.2359067430452715.

🏃 View run bald-foal-323 at: http://127.0.0.1:5000/#/experiments/1/runs/c7a91f9fa9e14348825db25f4912c9a8
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

[I 2026-04-11 15:55:14,943] Trial 12 finished with value: 0.23288864439990445 and parameters: {'n_estimators': 574, 'max_depth': 15, 'learning_rate': 0.016123828890854962, 'subsample': 0.9929561436209847, 'colsample_bytree': 0.8006591768020518, 'gamma': 2.92873807384593, 'scale_pos_weight': 1.187444824704312}. Best is trial 5 with value: 0.2359067430452715.

🏃 View run capable-seal-594 at: http://127.0.0.1:5000/#/experiments/1/runs/1aaf04d4bcdd4dabb8587d33b914b3db
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

[I 2026-04-11 15:55:24,078] Trial 13 finished with value: 0.2339954480571373 and parameters: {'n_estimators': 629, 'max_depth': 8, 'learning_rate': 0.020191733053441005, 'subsample': 0.9341566575202154, 'colsample_bytree': 0.8072377152571838, 'gamma': 2.92236037265724, 'scale_pos_weight': 1.9283725252521318}. Best is trial 5 with value: 0.2359067430452715.

🏃 View run fearless-worm-31 at: http://127.0.0.1:5000/#/experiments/1/runs/306cce6b0cc84e1097faee6bf788fb49
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

[I 2026-04-11 15:55:35,788] Trial 14 finished with value: 0.23026970799603833 and parameters: {'n_estimators': 690, 'max_depth': 8, 'learning_rate': 0.020992021237489396, 'subsample': 0.906239043328551, 'colsample_bytree': 0.8686382530004233, 'gamma': 2.531190820573323, 'scale_pos_weight': 3.6592319755128617}. Best is trial 5 with value: 0.2359067430452715.

🏃 View run nebulous-gull-773 at: http://127.0.0.1:5000/#/experiments/1/runs/71ef2ec2b8b344cd9ffff05353c28b92
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

[I 2026-04-11 15:55:44,543] Trial 15 finished with value: 0.23530789992677956 and parameters: {'n_estimators': 716, 'max_depth': 5, 'learning_rate': 0.02704735502396999, 'subsample': 0.7703941061491829, 'colsample_bytree': 0.8971453174804497, 'gamma': 4.8688783474244826, 'scale_pos_weight': 1.9711118552928977}. Best is trial 5 with value: 0.2359067430452715.

🏃 View run bustling-lamb-621 at: http://127.0.0.1:5000/#/experiments/1/runs/a20bf21ab2164d8690827e7358f22473
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

[I 2026-04-11 15:55:55,159] Trial 16 finished with value: 0.2098278037177041 and parameters: {'n_estimators': 980, 'max_depth': 5, 'learning_rate': 0.2814199602521279, 'subsample': 0.7563462674055702, 'colsample_bytree': 0.8981503003259479, 'gamma': 4.955778115260733, 'scale_pos_weight': 4.542144120906381}. Best is trial 5 with value: 0.2359067430452715.

🏃 View run flawless-crane-969 at: http://127.0.0.1:5000/#/experiments/1/runs/c2e36b726fd44ae6b8b1a981592473bd
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

[I 2026-04-11 15:56:03,374] Trial 17 finished with value: 0.23232696823965887 and parameters: {'n_estimators': 740, 'max_depth': 5, 'learning_rate': 0.08180017883708518, 'subsample': 0.7651899213381016, 'colsample_bytree': 0.738323641874029, 'gamma': 4.994944867000743, 'scale_pos_weight': 2.075411717550206}. Best is trial 5 with value: 0.2359067430452715.

🏃 View run dazzling-mole-12 at: http://127.0.0.1:5000/#/experiments/1/runs/3711f07038f14b508d8a4d37fc0d6b85
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

[I 2026-04-11 15:56:12,375] Trial 18 finished with value: 0.2293993237194272 and parameters: {'n_estimators': 421, 'max_depth': 7, 'learning_rate': 0.02715320234440602, 'subsample': 0.7093009833913421, 'colsample_bytree': 0.9396546310800507, 'gamma': 1.8038557741139076, 'scale_pos_weight': 3.5360567741519278}. Best is trial 5 with value: 0.2359067430452715.

🏃 View run fun-conch-913 at: http://127.0.0.1:5000/#/experiments/1/runs/4a9c05ed828d471f81d6812a26c7ed34
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

[I 2026-04-11 15:56:23,245] Trial 19 finished with value: 0.22124519689390365 and parameters: {'n_estimators': 850, 'max_depth': 5, 'learning_rate': 0.06962065961011593, 'subsample': 0.8014235148915644, 'colsample_bytree': 0.6112041757868888, 'gamma': 3.6285053575127257, 'scale_pos_weight': 5.361410119189568}. Best is trial 5 with value: 0.2359067430452715.

🏃 View run clumsy-crane-179 at: http://127.0.0.1:5000/#/experiments/1/runs/74e018078ed34f03b602c74caa80b815
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

[I 2026-04-11 15:56:28,095] Trial 20 finished with value: 0.22032420201565814 and parameters: {'n_estimators': 303, 'max_depth': 7, 'learning_rate': 0.12390019047956885, 'subsample': 0.5376540928510731, 'colsample_bytree': 0.8470137775232447, 'gamma': 4.5584800408172, 'scale_pos_weight': 1.8099640320588413}. Best is trial 5 with value: 0.2359067430452715.

🏃 View run merciful-yak-965 at: http://127.0.0.1:5000/#/experiments/1/runs/264df003ccff4349aece5088a765fa57
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

[I 2026-04-11 15:56:37,204] Trial 21 finished with value: 0.23489129995250685 and parameters: {'n_estimators': 633, 'max_depth': 8, 'learning_rate': 0.022093414204663663, 'subsample': 0.9219283701590748, 'colsample_bytree': 0.7998056894753779, 'gamma': 2.9144175559931735, 'scale_pos_weight': 1.8099516183052349}. Best is trial 5 with value: 0.2359067430452715.

🏃 View run melodic-crow-850 at: http://127.0.0.1:5000/#/experiments/1/runs/28a7e7fdeef44de3ac8fd1287b9b1cdc
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

[I 2026-04-11 15:56:46,821] Trial 22 finished with value: 0.2356956830114921 and parameters: {'n_estimators': 670, 'max_depth': 6, 'learning_rate': 0.026910541649718723, 'subsample': 0.8396681361964916, 'colsample_bytree': 0.7589880584176089, 'gamma': 2.9577041440059055, 'scale_pos_weight': 1.720169463460492}. Best is trial 5 with value: 0.2359067430452715.

🏃 View run polite-sow-531 at: http://127.0.0.1:5000/#/experiments/1/runs/dbe653950abf4aa9972a04d3bbd6422a
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

[I 2026-04-11 15:56:55,747] Trial 23 finished with value: 0.23080668901513096 and parameters: {'n_estimators': 529, 'max_depth': 6, 'learning_rate': 0.026395714444564643, 'subsample': 0.8385303600021481, 'colsample_bytree': 0.7408646900521358, 'gamma': 2.317973746073268, 'scale_pos_weight': 3.012223592249546}. Best is trial 5 with value: 0.2359067430452715.

🏃 View run spiffy-ox-838 at: http://127.0.0.1:5000/#/experiments/1/runs/47f02acbf42942af9ab1385354a25f49
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

[I 2026-04-11 15:57:07,226] Trial 24 finished with value: 0.23476493550203634 and parameters: {'n_estimators': 769, 'max_depth': 5, 'learning_rate': 0.014736593516732798, 'subsample': 0.7762721918955336, 'colsample_bytree': 0.6408753084359807, 'gamma': 3.8079147261647344, 'scale_pos_weight': 2.4498460024911335}. Best is trial 5 with value: 0.2359067430452715.

🏃 View run adventurous-bass-518 at: http://127.0.0.1:5000/#/experiments/1/runs/016fccaf84c2480b9455baab8be0f76f
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

[I 2026-04-11 15:57:14,896] Trial 25 finished with value: 0.2339665172308101 and parameters: {'n_estimators': 679, 'max_depth': 6, 'learning_rate': 0.05076746801162815, 'subsample': 0.8517128482074325, 'colsample_bytree': 0.8898819800617072, 'gamma': 3.186738751709748, 'scale_pos_weight': 1.4757846780383297}. Best is trial 5 with value: 0.2359067430452715.

🏃 View run classy-shrew-750 at: http://127.0.0.1:5000/#/experiments/1/runs/e9e87ac2fd98431fa031cd8d32baf9da
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

[I 2026-04-11 15:57:24,039] Trial 26 finished with value: 0.23089857943934217 and parameters: {'n_estimators': 563, 'max_depth': 5, 'learning_rate': 0.030728597583627316, 'subsample': 0.7977771248389304, 'colsample_bytree': 0.93118922730121, 'gamma': 1.9851623213834733, 'scale_pos_weight': 3.4491378463471696}. Best is trial 5 with value: 0.2359067430452715.

🏃 View run beautiful-smelt-303 at: http://127.0.0.1:5000/#/experiments/1/runs/097b938dac77424fae1952e0aa1d8bca
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

[I 2026-04-11 15:57:36,889] Trial 27 finished with value: 0.21650422297304997 and parameters: {'n_estimators': 900, 'max_depth': 11, 'learning_rate': 0.0928596956173947, 'subsample': 0.7111667730765072, 'colsample_bytree': 0.766842670260344, 'gamma': 1.306437962712478, 'scale_pos_weight': 2.1831422583661455}. Best is trial 5 with value: 0.2359067430452715.

🏃 View run beautiful-loon-348 at: http://127.0.0.1:5000/#/experiments/1/runs/4dfd238704dc46fa8465a1a0f917ac00
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

[I 2026-04-11 15:57:45,647] Trial 28 finished with value: 0.23273616141502393 and parameters: {'n_estimators': 780, 'max_depth': 7, 'learning_rate': 0.04325547166657721, 'subsample': 0.901976722488553, 'colsample_bytree': 0.6683265163782456, 'gamma': 2.548758925943761, 'scale_pos_weight': 1.5057740458318518}. Best is trial 5 with value: 0.2359067430452715.

🏃 View run kindly-lamb-222 at: http://127.0.0.1:5000/#/experiments/1/runs/014e6ca31ae2494eba993d446ee89214
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

[I 2026-04-11 15:57:53,323] Trial 29 finished with value: 0.2361648634294333 and parameters: {'n_estimators': 696, 'max_depth': 6, 'learning_rate': 0.05448844416988449, 'subsample': 0.9483060512019015, 'colsample_bytree': 0.5311783295444403, 'gamma': 4.075611858401903, 'scale_pos_weight': 4.3210092387214365}. Best is trial 29 with value: 0.2361648634294333.

🏃 View run nosy-mare-354 at: http://127.0.0.1:5000/#/experiments/1/runs/ab13df7c1e67464e90dad87bb7701cb1
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

[I 2026-04-11 15:58:00,639] Trial 30 finished with value: 0.23396483561006137 and parameters: {'n_estimators': 650, 'max_depth': 9, 'learning_rate': 0.05128006878998333, 'subsample': 0.9613899688005976, 'colsample_bytree': 0.5267610319796234, 'gamma': 4.108888954788884, 'scale_pos_weight': 4.346361642097186}. Best is trial 29 with value: 0.2361648634294333.

🏃 View run invincible-shoat-692 at: http://127.0.0.1:5000/#/experiments/1/runs/34a41811ae1545ea83b843fe05e19ff1
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

[I 2026-04-11 15:58:10,258] Trial 31 finished with value: 0.22904278751043033 and parameters: {'n_estimators': 722, 'max_depth': 6, 'learning_rate': 0.062488701171573124, 'subsample': 0.6720659210198008, 'colsample_bytree': 0.5808347594606653, 'gamma': 4.640801041281769, 'scale_pos_weight': 2.9462532072263987}. Best is trial 29 with value: 0.2361648634294333.

🏃 View run unruly-doe-67 at: http://127.0.0.1:5000/#/experiments/1/runs/d7fd013e7f1a467c91d4427d5869de39
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

[I 2026-04-11 15:58:19,063] Trial 32 finished with value: 0.22965557761898853 and parameters: {'n_estimators': 584, 'max_depth': 6, 'learning_rate': 0.03550928647469864, 'subsample': 0.8263939820113286, 'colsample_bytree': 0.5088785001437973, 'gamma': 3.25552987900951, 'scale_pos_weight': 5.034944649154588}. Best is trial 29 with value: 0.2361648634294333.

🏃 View run inquisitive-skink-7 at: http://127.0.0.1:5000/#/experiments/1/runs/46f466f24aa045fbad88fe1e5c08b77d
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

[I 2026-04-11 15:58:26,189] Trial 33 finished with value: 0.2313437213936514 and parameters: {'n_estimators': 706, 'max_depth': 6, 'learning_rate': 0.0953594630013823, 'subsample': 0.9530023518914217, 'colsample_bytree': 0.7437111123414251, 'gamma': 3.5345124122043647, 'scale_pos_weight': 4.180659896493177}. Best is trial 29 with value: 0.2361648634294333.

🏃 View run caring-perch-352 at: http://127.0.0.1:5000/#/experiments/1/runs/48364feb42e54ba2948c44eddcd213b9
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

[I 2026-04-11 15:58:37,548] Trial 34 finished with value: 0.23388580467993855 and parameters: {'n_estimators': 821, 'max_depth': 5, 'learning_rate': 0.016417251006488685, 'subsample': 0.8787628204572917, 'colsample_bytree': 0.7079318157605394, 'gamma': 4.0836530335851915, 'scale_pos_weight': 5.209589554262088}. Best is trial 29 with value: 0.2361648634294333.

🏃 View run learned-cod-310 at: http://127.0.0.1:5000/#/experiments/1/runs/ec573f01291a4729a97895cd008021be
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

[I 2026-04-11 15:58:46,718] Trial 35 finished with value: 0.23635430229810034 and parameters: {'n_estimators': 783, 'max_depth': 7, 'learning_rate': 0.029625295404581753, 'subsample': 0.7395907364811722, 'colsample_bytree': 0.6627663798698511, 'gamma': 4.719006835416357, 'scale_pos_weight': 1.5008361948733273}. Best is trial 35 with value: 0.23635430229810034.

🏃 View run thundering-zebra-839 at: http://127.0.0.1:5000/#/experiments/1/runs/35bb38afd2dd470b9a0d76ce8a6b5b71
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

[I 2026-04-11 15:59:00,142] Trial 36 finished with value: 0.224146888548766 and parameters: {'n_estimators': 912, 'max_depth': 9, 'learning_rate': 0.044226956174266925, 'subsample': 0.6193177891384685, 'colsample_bytree': 0.5701347611800265, 'gamma': 4.331923253122428, 'scale_pos_weight': 5.518013934507086}. Best is trial 35 with value: 0.23635430229810034.

🏃 View run angry-cat-938 at: http://127.0.0.1:5000/#/experiments/1/runs/35f5b38197ce4616ac3c22c9dc173d25
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

[I 2026-04-11 15:59:08,501] Trial 37 finished with value: 0.23598674496374167 and parameters: {'n_estimators': 790, 'max_depth': 7, 'learning_rate': 0.059330418586263214, 'subsample': 0.8653224378749682, 'colsample_bytree': 0.6587330025929199, 'gamma': 3.7939270895427155, 'scale_pos_weight': 1.4796184050091974}. Best is trial 35 with value: 0.23635430229810034.

🏃 View run grandiose-vole-848 at: http://127.0.0.1:5000/#/experiments/1/runs/4f2d3e26e7ee4778a53d9b9a169b8614
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

[I 2026-04-11 15:59:24,211] Trial 38 finished with value: 0.21645728030369493 and parameters: {'n_estimators': 795, 'max_depth': 7, 'learning_rate': 0.06298397009322218, 'subsample': 0.8656767898715818, 'colsample_bytree': 0.6498383916020981, 'gamma': 0.17922616271767344, 'scale_pos_weight': 3.9778124139929614}. Best is trial 35 with value: 0.23635430229810034.

🏃 View run suave-dolphin-496 at: http://127.0.0.1:5000/#/experiments/1/runs/24737504b25b49d3923e8390d36102e6
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

[I 2026-04-11 15:59:35,304] Trial 39 finished with value: 0.21874256347366589 and parameters: {'n_estimators': 971, 'max_depth': 8, 'learning_rate': 0.16058873725890702, 'subsample': 0.7324152211074682, 'colsample_bytree': 0.6076172711817645, 'gamma': 3.808566418709982, 'scale_pos_weight': 2.5486396386778103}. Best is trial 35 with value: 0.23635430229810034.

🏃 View run adorable-boar-799 at: http://127.0.0.1:5000/#/experiments/1/runs/cf49996fdac6425f804aa1c32158fb5d
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

[I 2026-04-11 15:59:45,315] Trial 40 finished with value: 0.23656676723876732 and parameters: {'n_estimators': 864, 'max_depth': 7, 'learning_rate': 0.07404870294862903, 'subsample': 0.8920832774235486, 'colsample_bytree': 0.5456467971931089, 'gamma': 4.65970500666878, 'scale_pos_weight': 1.370916242370779}. Best is trial 40 with value: 0.23656676723876732.

🏃 View run intelligent-fish-745 at: http://127.0.0.1:5000/#/experiments/1/runs/359e0165b25a401ba593134fdfa5ee61
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

[I 2026-04-11 15:59:53,743] Trial 41 finished with value: 0.23548725816822963 and parameters: {'n_estimators': 879, 'max_depth': 9, 'learning_rate': 0.07554504350415918, 'subsample': 0.8918878441831259, 'colsample_bytree': 0.5460133563968533, 'gamma': 4.58833445093705, 'scale_pos_weight': 1.3913061519899907}. Best is trial 40 with value: 0.23656676723876732.

🏃 View run gregarious-lynx-413 at: http://127.0.0.1:5000/#/experiments/1/runs/fd8ee246ab0b45128073ae8b52727d32
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

[I 2026-04-11 16:00:01,985] Trial 42 finished with value: 0.23424357884991256 and parameters: {'n_estimators': 758, 'max_depth': 7, 'learning_rate': 0.09884517481485766, 'subsample': 0.9312215768870608, 'colsample_bytree': 0.5768868915340605, 'gamma': 4.124566402298909, 'scale_pos_weight': 2.2493164634309935}. Best is trial 40 with value: 0.23656676723876732.

🏃 View run bright-pug-939 at: http://127.0.0.1:5000/#/experiments/1/runs/4afa4703df8b488ea0fb2033bce53700
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

[I 2026-04-11 16:00:10,048] Trial 43 finished with value: 0.23408670461290507 and parameters: {'n_estimators': 858, 'max_depth': 8, 'learning_rate': 0.05626884864373274, 'subsample': 0.9633998166551724, 'colsample_bytree': 0.508346080393026, 'gamma': 3.505979710931035, 'scale_pos_weight': 1.495210801118205}. Best is trial 40 with value: 0.23656676723876732.

🏃 View run whimsical-owl-878 at: http://127.0.0.1:5000/#/experiments/1/runs/fd37c2685e354da490c687028085237f
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

[I 2026-04-11 16:00:19,348] Trial 44 finished with value: 0.2273930096754678 and parameters: {'n_estimators': 956, 'max_depth': 7, 'learning_rate': 0.10913466923587081, 'subsample': 0.8115845701193789, 'colsample_bytree': 0.5452126459236281, 'gamma': 4.415278299705886, 'scale_pos_weight': 2.783614214761146}. Best is trial 40 with value: 0.23656676723876732.

🏃 View run beautiful-stork-565 at: http://127.0.0.1:5000/#/experiments/1/runs/4b6a1db381fb4b629dfa62a381a75093
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

[I 2026-04-11 16:00:27,416] Trial 45 finished with value: 0.23469973525769386 and parameters: {'n_estimators': 809, 'max_depth': 7, 'learning_rate': 0.03750899288059907, 'subsample': 0.9116285420532415, 'colsample_bytree': 0.6309827119118554, 'gamma': 3.9584855692672325, 'scale_pos_weight': 1.0444086534837722}. Best is trial 40 with value: 0.23656676723876732.

🏃 View run kindly-grouse-147 at: http://127.0.0.1:5000/#/experiments/1/runs/43e795f07f764af3b568ef3a4b274198
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

[I 2026-04-11 16:00:33,845] Trial 46 finished with value: 0.22565172276468753 and parameters: {'n_estimators': 601, 'max_depth': 9, 'learning_rate': 0.08249949984413221, 'subsample': 0.8719889842417838, 'colsample_bytree': 0.6854139887173172, 'gamma': 4.686531852288727, 'scale_pos_weight': 4.717894062388869}. Best is trial 40 with value: 0.23656676723876732.

🏃 View run victorious-shrew-212 at: http://127.0.0.1:5000/#/experiments/1/runs/5f54f1bd89bf416986781c570f45b1c7
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

[I 2026-04-11 16:00:43,002] Trial 47 finished with value: 0.23410727128036868 and parameters: {'n_estimators': 924, 'max_depth': 10, 'learning_rate': 0.0694091645460134, 'subsample': 0.9422434089002688, 'colsample_bytree': 0.6009298738318356, 'gamma': 4.342412745816496, 'scale_pos_weight': 1.2738213108943022}. Best is trial 40 with value: 0.23656676723876732.

🏃 View run bedecked-auk-915 at: http://127.0.0.1:5000/#/experiments/1/runs/ad3368b9ff3840a59ee05335d1c49b03
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

[I 2026-04-11 16:00:50,368] Trial 48 finished with value: 0.23412977589874842 and parameters: {'n_estimators': 747, 'max_depth': 14, 'learning_rate': 0.19842015227428594, 'subsample': 0.8584298239881051, 'colsample_bytree': 0.7122781646317752, 'gamma': 4.76038792585919, 'scale_pos_weight': 1.0074767490574341}. Best is trial 40 with value: 0.23656676723876732.

🏃 View run valuable-mule-509 at: http://127.0.0.1:5000/#/experiments/1/runs/8c8871b6085e460c90debda13d86229a
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

[I 2026-04-11 16:01:00,737] Trial 49 finished with value: 0.2175546446361968 and parameters: {'n_estimators': 836, 'max_depth': 11, 'learning_rate': 0.13390127816381694, 'subsample': 0.6798938289835931, 'colsample_bytree': 0.5621367140042131, 'gamma': 3.7099864983752515, 'scale_pos_weight': 3.3048393242981984}. Best is trial 40 with value: 0.23656676723876732.

🏃 View run casual-bug-151 at: http://127.0.0.1:5000/#/experiments/1/runs/027671faa3da4acdb429d675ceef4ec0
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1
----------------------------------------
XGBoost tuning completed!
Best CV PR-AUC: 0.2366
Test PR-AUC: 0.2351
Best Parameters: {'n_estimators': 864, 'max_depth': 7, 'learning_rate': 0.07404870294862903, 'subsample': 0.8920832774235486, 'colsample_bytree': 0.5456467971931089, 'gamma': 4.65970500666878, 'scale_pos_weight': 1.370916242370779}
🏃 View run XGBoost_PR_AUC_Optimization_CV at: http://127.0.0.1:5000/#/experiments/1/runs/3eb1e97d58a5486694e662bf964301f9
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

In [ ]:
# # Vẽ ma trận nhầm lẫn chuẩn hóa (normalized) theo hàng ngang (true labels)
# fig, ax = plt.subplots(figsize=(8, 6))
# disp_norm = ConfusionMatrixDisplay.from_estimator(
#     best_xgb,
#     X_test,
#     y_test,
#     display_labels=["Active (0)", "Churn (1)"],
#     cmap="Greens",
#     normalize='true', # Quan trọng: tính % theo từng lớp thực tế
#     ax=ax
# )

# plt.title("Normalized Confusion Matrix (%)")
# plt.show()

### LIGHTGBM

In [14]:
# =========================================
# LightGBM tuning with CV
# =========================================
def objective_lgbm(trial):
    """
    Tune LightGBM using cross-validated PR-AUC on the training set only.
    This avoids test leakage during hyperparameter search.
    """
    params = {
        "n_estimators": trial.suggest_int("n_estimators", 300, 1200),
        "learning_rate": trial.suggest_float("learning_rate", 0.005, 0.1, log=True),
        "num_leaves": trial.suggest_int("num_leaves", 20, 150),
        "max_depth": trial.suggest_int("max_depth", 3, 12),
        "min_child_samples": trial.suggest_int("min_child_samples", 20, 100),
        "scale_pos_weight": trial.suggest_float("scale_pos_weight", 1.0, ratio * 1.5),
        "reg_alpha": trial.suggest_float("reg_alpha", 1e-3, 10.0, log=True),
        "reg_lambda": trial.suggest_float("reg_lambda", 1e-3, 10.0, log=True),
        "random_state": RANDOM_STATE,
        "verbosity": -1,
        "n_jobs": -1,
    }

    model = LGBMClassifier(**params)

    # Out-of-fold predicted probabilities on training data
    y_proba_oof = cross_val_predict(
        estimator=model,
        X=X_train,
        y=y_train,
        cv=cv,
        method="predict_proba",
        n_jobs=-1,
    )[:, 1]

    # Default classification threshold for reporting auxiliary metrics
    y_pred_oof = (y_proba_oof >= 0.5).astype(int)

    metrics = {
        "cv_pr_auc": float(average_precision_score(y_train, y_proba_oof)),
        "cv_roc_auc": float(roc_auc_score(y_train, y_proba_oof)),
        "cv_log_loss": float(log_loss(y_train, y_proba_oof)),
        "cv_accuracy": float(accuracy_score(y_train, y_pred_oof)),
        "cv_precision": float(precision_score(y_train, y_pred_oof, zero_division=0)),
        "cv_recall": float(recall_score(y_train, y_pred_oof, zero_division=0)),
        "cv_f1_score": float(f1_score(y_train, y_pred_oof, zero_division=0)),
    }

    # Log each Optuna trial as a nested MLflow run
    with mlflow.start_run(nested=True):
        mlflow.log_params(params)
        mlflow.log_metrics(metrics)

    return metrics["cv_pr_auc"]


with mlflow.start_run(run_name="LGBM_PR_AUC_Optimization_CV"):
    logger.info("Starting LightGBM hyperparameter tuning with Stratified CV...")

    study_lgbm = optuna.create_study(direction="maximize")
    study_lgbm.optimize(objective_lgbm, n_trials=50)

    # Log best CV result
    mlflow.log_params(study_lgbm.best_params)
    mlflow.log_metric("best_cv_pr_auc", float(study_lgbm.best_value))

    # Train final LightGBM model on full training set with best params
    best_lgbm = LGBMClassifier(
        **study_lgbm.best_params,
        random_state=RANDOM_STATE,
        verbosity=-1,
        n_jobs=-1,
    )
    best_lgbm.fit(X_train, y_train)

    # Final evaluation on untouched test set
    y_test_proba = best_lgbm.predict_proba(X_test)[:, 1]
    y_test_pred = (y_test_proba >= 0.5).astype(int)

    test_metrics = {
        "test_pr_auc": float(average_precision_score(y_test, y_test_proba)),
        "test_roc_auc": float(roc_auc_score(y_test, y_test_proba)),
        "test_log_loss": float(log_loss(y_test, y_test_proba)),
        "test_accuracy": float(accuracy_score(y_test, y_test_pred)),
        "test_precision": float(precision_score(y_test, y_test_pred, zero_division=0)),
        "test_recall": float(recall_score(y_test, y_test_pred, zero_division=0)),
        "test_f1_score": float(f1_score(y_test, y_test_pred, zero_division=0)),
    }

    mlflow.log_metrics(test_metrics)
    mlflow.lightgbm.log_model(best_lgbm, name="best_lgbm_prauc_model")

    overall_results["LightGBM"] = {
        "model": best_lgbm,
        "cv_pr_auc": float(study_lgbm.best_value),
        "test_pr_auc": float(test_metrics["test_pr_auc"]),
        "params": study_lgbm.best_params,
    }

    print("-" * 40)
    print("LightGBM tuning completed!")
    print(f"Best CV PR-AUC: {study_lgbm.best_value:.4f}")
    print(f"Test PR-AUC: {test_metrics['test_pr_auc']:.4f}")
    print(f"Best Parameters: {study_lgbm.best_params}")

2026-04-11 16:11:11 [INFO] Starting LightGBM hyperparameter tuning with Stratified CV...
[I 2026-04-11 16:11:11,461] A new study created in memory with name: no-name-df7fd5f7-5435-4b4b-ae6c-606721562cc1
[I 2026-04-11 16:11:57,182] Trial 0 finished with value: 0.21097507225828804 and parameters: {'n_estimators': 1067, 'learning_rate': 0.08264823360870166, 'num_leaves': 132, 'max_depth': 7, 'min_child_samples': 25, 'scale_pos_weight': 3.373673084863828, 'reg_alpha': 0.9122961235009924, 'reg_lambda': 0.011247157977812259}. Best is trial 0 with value: 0.21097507225828804.

🏃 View run unequaled-hawk-345 at: http://127.0.0.1:5000/#/experiments/1/runs/cadf13c58d664377bc233fa15df8b859
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

[I 2026-04-11 16:12:21,071] Trial 1 finished with value: 0.23041814969168448 and parameters: {'n_estimators': 1117, 'learning_rate': 0.031716954893400685, 'num_leaves': 32, 'max_depth': 4, 'min_child_samples': 79, 'scale_pos_weight': 6.748875722002325, 'reg_alpha': 2.2512233207784185, 'reg_lambda': 0.1839614146787839}. Best is trial 1 with value: 0.23041814969168448.

🏃 View run smiling-goose-464 at: http://127.0.0.1:5000/#/experiments/1/runs/056af7114688415a9c85b848f4a7e951
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

[I 2026-04-11 16:12:47,581] Trial 2 finished with value: 0.23639042295652035 and parameters: {'n_estimators': 423, 'learning_rate': 0.005585042900747331, 'num_leaves': 131, 'max_depth': 9, 'min_child_samples': 30, 'scale_pos_weight': 3.955036792216239, 'reg_alpha': 3.8126894004910596, 'reg_lambda': 0.001152336396292018}. Best is trial 2 with value: 0.23639042295652035.

🏃 View run abrasive-hen-978 at: http://127.0.0.1:5000/#/experiments/1/runs/6896d733406749d29df20de89dc6a7dd
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

[I 2026-04-11 16:13:16,604] Trial 3 finished with value: 0.22699676270536204 and parameters: {'n_estimators': 1195, 'learning_rate': 0.019174260962618202, 'num_leaves': 47, 'max_depth': 9, 'min_child_samples': 59, 'scale_pos_weight': 6.374222558447774, 'reg_alpha': 0.016028841142282115, 'reg_lambda': 0.026289516516171958}. Best is trial 2 with value: 0.23639042295652035.

🏃 View run worried-rook-734 at: http://127.0.0.1:5000/#/experiments/1/runs/1e1478f32a9748acb756043cb4b0af9f
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

[I 2026-04-11 16:13:20,761] Trial 4 finished with value: 0.23384072293057906 and parameters: {'n_estimators': 381, 'learning_rate': 0.032543614228264225, 'num_leaves': 118, 'max_depth': 4, 'min_child_samples': 96, 'scale_pos_weight': 7.102872461747792, 'reg_alpha': 0.694031843204277, 'reg_lambda': 0.43121348968872963}. Best is trial 2 with value: 0.23639042295652035.

🏃 View run auspicious-worm-882 at: http://127.0.0.1:5000/#/experiments/1/runs/43a3103aa42f4b7c8c5225f0f091cd22
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

[I 2026-04-11 16:13:38,531] Trial 5 finished with value: 0.23347401931080564 and parameters: {'n_estimators': 1013, 'learning_rate': 0.010517902953703761, 'num_leaves': 120, 'max_depth': 6, 'min_child_samples': 63, 'scale_pos_weight': 2.029414141477713, 'reg_alpha': 0.8919483639018575, 'reg_lambda': 5.316926011777902}. Best is trial 2 with value: 0.23639042295652035.

🏃 View run gifted-midge-669 at: http://127.0.0.1:5000/#/experiments/1/runs/a5c11e44929641ac963130315444e2b1
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

[I 2026-04-11 16:13:54,743] Trial 6 finished with value: 0.23214123752888088 and parameters: {'n_estimators': 591, 'learning_rate': 0.008671889233869693, 'num_leaves': 72, 'max_depth': 10, 'min_child_samples': 34, 'scale_pos_weight': 3.69531499010238, 'reg_alpha': 1.3638818734226241, 'reg_lambda': 0.5635516208732161}. Best is trial 2 with value: 0.23639042295652035.

🏃 View run enthused-bee-281 at: http://127.0.0.1:5000/#/experiments/1/runs/f28b970a6223488c870a76c412a78762
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

[I 2026-04-11 16:14:03,981] Trial 7 finished with value: 0.2283411809578121 and parameters: {'n_estimators': 449, 'learning_rate': 0.03267898593938865, 'num_leaves': 84, 'max_depth': 6, 'min_child_samples': 64, 'scale_pos_weight': 5.81736575729777, 'reg_alpha': 1.4202753060072972, 'reg_lambda': 1.151873934649355}. Best is trial 2 with value: 0.23639042295652035.

🏃 View run loud-bear-611 at: http://127.0.0.1:5000/#/experiments/1/runs/1bf1a0592d4e4180ab8092f113ec6669
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

[I 2026-04-11 16:14:45,110] Trial 8 finished with value: 0.2336976260737028 and parameters: {'n_estimators': 508, 'learning_rate': 0.006027590396023792, 'num_leaves': 122, 'max_depth': 12, 'min_child_samples': 89, 'scale_pos_weight': 2.0258425919785346, 'reg_alpha': 0.035244888506209326, 'reg_lambda': 0.09702886416155532}. Best is trial 2 with value: 0.23639042295652035.

🏃 View run bold-midge-988 at: http://127.0.0.1:5000/#/experiments/1/runs/f6c4fbe9b0664c268263b9ca924260f2
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

[I 2026-04-11 16:15:46,257] Trial 9 finished with value: 0.2310401322333697 and parameters: {'n_estimators': 988, 'learning_rate': 0.020603390894533797, 'num_leaves': 57, 'max_depth': 5, 'min_child_samples': 20, 'scale_pos_weight': 1.4449838084012043, 'reg_alpha': 0.0059298214929496326, 'reg_lambda': 2.1672813278141816}. Best is trial 2 with value: 0.23639042295652035.

🏃 View run debonair-fish-701 at: http://127.0.0.1:5000/#/experiments/1/runs/9f754a836ec44f41a56537b6d1796a2c
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

[I 2026-04-11 16:16:44,390] Trial 10 finished with value: 0.23581236114061502 and parameters: {'n_estimators': 777, 'learning_rate': 0.005248937470196875, 'num_leaves': 148, 'max_depth': 9, 'min_child_samples': 43, 'scale_pos_weight': 5.099411105832948, 'reg_alpha': 8.662966737146547, 'reg_lambda': 0.0010452581355382988}. Best is trial 2 with value: 0.23639042295652035.

🏃 View run awesome-horse-519 at: http://127.0.0.1:5000/#/experiments/1/runs/581d55990136447ab935b9653f8f09a9
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

[I 2026-04-11 16:17:19,177] Trial 11 finished with value: 0.23549329373917743 and parameters: {'n_estimators': 734, 'learning_rate': 0.005509154642425302, 'num_leaves': 147, 'max_depth': 9, 'min_child_samples': 41, 'scale_pos_weight': 4.919791729479519, 'reg_alpha': 9.30230721186751, 'reg_lambda': 0.0011775943140209847}. Best is trial 2 with value: 0.23639042295652035.

🏃 View run nebulous-moth-982 at: http://127.0.0.1:5000/#/experiments/1/runs/4b854e93c93b4c349becb6393026225c
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

[I 2026-04-11 16:18:11,859] Trial 12 finished with value: 0.2303293757919998 and parameters: {'n_estimators': 787, 'learning_rate': 0.010749353339504495, 'num_leaves': 149, 'max_depth': 11, 'min_child_samples': 47, 'scale_pos_weight': 4.8253780285473065, 'reg_alpha': 8.0969606389167, 'reg_lambda': 0.0012321780919956216}. Best is trial 2 with value: 0.23639042295652035.

🏃 View run able-ape-59 at: http://127.0.0.1:5000/#/experiments/1/runs/a7a666d03ec9441183693cc160dd91f3
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

[I 2026-04-11 16:18:22,602] Trial 13 finished with value: 0.23528640328776618 and parameters: {'n_estimators': 301, 'learning_rate': 0.007180515595186297, 'num_leaves': 101, 'max_depth': 8, 'min_child_samples': 47, 'scale_pos_weight': 4.604727505404236, 'reg_alpha': 0.20232858079706245, 'reg_lambda': 0.005204495933979694}. Best is trial 2 with value: 0.23639042295652035.

🏃 View run rumbling-mink-842 at: http://127.0.0.1:5000/#/experiments/1/runs/57da6c8e8c34456a8ba1cfb2c26cb02f
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

[I 2026-04-11 16:18:50,994] Trial 14 finished with value: 0.22692295379022226 and parameters: {'n_estimators': 821, 'learning_rate': 0.01309712892782604, 'num_leaves': 97, 'max_depth': 10, 'min_child_samples': 34, 'scale_pos_weight': 3.079513038949121, 'reg_alpha': 0.001705704946767048, 'reg_lambda': 0.0035925893055687185}. Best is trial 2 with value: 0.23639042295652035.

🏃 View run debonair-vole-59 at: http://127.0.0.1:5000/#/experiments/1/runs/eebba085d7c3431db740d05a4302e0da
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

[I 2026-04-11 16:19:14,777] Trial 15 finished with value: 0.23668976345923343 and parameters: {'n_estimators': 619, 'learning_rate': 0.005182269763884033, 'num_leaves': 137, 'max_depth': 8, 'min_child_samples': 54, 'scale_pos_weight': 5.184242584158063, 'reg_alpha': 0.23321383868048798, 'reg_lambda': 0.043659031808266247}. Best is trial 15 with value: 0.23668976345923343.

🏃 View run debonair-horse-952 at: http://127.0.0.1:5000/#/experiments/1/runs/cc0a968a6d1e4c0ba7064fe0690b7d7f
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

[I 2026-04-11 16:19:30,865] Trial 16 finished with value: 0.21473138741621717 and parameters: {'n_estimators': 620, 'learning_rate': 0.08330640957332429, 'num_leaves': 109, 'max_depth': 7, 'min_child_samples': 74, 'scale_pos_weight': 5.820497863671692, 'reg_alpha': 0.08811466374793145, 'reg_lambda': 0.029283846251623228}. Best is trial 15 with value: 0.23668976345923343.

🏃 View run capricious-trout-779 at: http://127.0.0.1:5000/#/experiments/1/runs/fd104607210b46cbbbdf6b93a7aa48a3
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

[I 2026-04-11 16:19:51,794] Trial 17 finished with value: 0.22961178269963536 and parameters: {'n_estimators': 601, 'learning_rate': 0.012875501933045127, 'num_leaves': 134, 'max_depth': 8, 'min_child_samples': 54, 'scale_pos_weight': 4.113467326663891, 'reg_alpha': 0.23567213355028355, 'reg_lambda': 0.07020238798535465}. Best is trial 15 with value: 0.23668976345923343.

🏃 View run colorful-ant-580 at: http://127.0.0.1:5000/#/experiments/1/runs/21e75b1ab27b4e17b90a96357e024d95
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

[I 2026-04-11 16:20:07,905] Trial 18 finished with value: 0.22251100214882247 and parameters: {'n_estimators': 482, 'learning_rate': 0.054587280670796205, 'num_leaves': 86, 'max_depth': 12, 'min_child_samples': 29, 'scale_pos_weight': 2.9705802753044455, 'reg_alpha': 0.3147725842611236, 'reg_lambda': 0.004932909886334191}. Best is trial 15 with value: 0.23668976345923343.

🏃 View run peaceful-penguin-605 at: http://127.0.0.1:5000/#/experiments/1/runs/17d7b468ff754c91a31f9c33f3312e4f
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

[I 2026-04-11 16:20:33,811] Trial 19 finished with value: 0.23108530305705605 and parameters: {'n_estimators': 689, 'learning_rate': 0.0077467068531809485, 'num_leaves': 134, 'max_depth': 10, 'min_child_samples': 73, 'scale_pos_weight': 5.626878139354622, 'reg_alpha': 3.360029251488411, 'reg_lambda': 0.01837638733769013}. Best is trial 15 with value: 0.23668976345923343.

🏃 View run shivering-cub-213 at: http://127.0.0.1:5000/#/experiments/1/runs/4d8302710cfc4ba2bedf54fcf5ab1b7f
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

[I 2026-04-11 16:20:48,240] Trial 20 finished with value: 0.2302103369932571 and parameters: {'n_estimators': 864, 'learning_rate': 0.015625668130367924, 'num_leaves': 106, 'max_depth': 6, 'min_child_samples': 54, 'scale_pos_weight': 4.171586450495721, 'reg_alpha': 0.05868044416894947, 'reg_lambda': 0.053433054423088606}. Best is trial 15 with value: 0.23668976345923343.

🏃 View run secretive-newt-584 at: http://127.0.0.1:5000/#/experiments/1/runs/01aa915f3c68463da7e500975f8e59a9
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

[I 2026-04-11 16:21:26,774] Trial 21 finished with value: 0.23511857100801622 and parameters: {'n_estimators': 905, 'learning_rate': 0.005045329857920915, 'num_leaves': 150, 'max_depth': 9, 'min_child_samples': 41, 'scale_pos_weight': 5.218174612879547, 'reg_alpha': 5.331982515455343, 'reg_lambda': 0.0021661844316381703}. Best is trial 15 with value: 0.23668976345923343.

🏃 View run puzzled-fox-725 at: http://127.0.0.1:5000/#/experiments/1/runs/f0327a8ef82b47289b073ea5116029ab
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

[I 2026-04-11 16:21:53,541] Trial 22 finished with value: 0.2319407589884887 and parameters: {'n_estimators': 678, 'learning_rate': 0.006917580866035541, 'num_leaves': 137, 'max_depth': 8, 'min_child_samples': 40, 'scale_pos_weight': 4.418627674947795, 'reg_alpha': 3.274467354348357, 'reg_lambda': 0.010634518048238877}. Best is trial 15 with value: 0.23668976345923343.

🏃 View run masked-carp-666 at: http://127.0.0.1:5000/#/experiments/1/runs/1d3b59aad3924650b3d9967ab31cb716
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

[I 2026-04-11 16:22:09,429] Trial 23 finished with value: 0.2324039648703219 and parameters: {'n_estimators': 400, 'learning_rate': 0.008876038981959471, 'num_leaves': 126, 'max_depth': 9, 'min_child_samples': 47, 'scale_pos_weight': 5.308209035025669, 'reg_alpha': 0.4050694422958494, 'reg_lambda': 0.0021401831852438827}. Best is trial 15 with value: 0.23668976345923343.

🏃 View run resilient-sloth-224 at: http://127.0.0.1:5000/#/experiments/1/runs/7cfe3481d3ff47ccb517aea9242de46a
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

[I 2026-04-11 16:22:37,897] Trial 24 finished with value: 0.2354613494926759 and parameters: {'n_estimators': 539, 'learning_rate': 0.005086460961285903, 'num_leaves': 140, 'max_depth': 11, 'min_child_samples': 33, 'scale_pos_weight': 3.709474432496178, 'reg_alpha': 4.172585206374922, 'reg_lambda': 0.008085042490324162}. Best is trial 15 with value: 0.23668976345923343.

🏃 View run sedate-shark-158 at: http://127.0.0.1:5000/#/experiments/1/runs/0765a67bb3f7415a93dacdc5991d4056
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

[I 2026-04-11 16:23:04,840] Trial 25 finished with value: 0.23195061147325985 and parameters: {'n_estimators': 686, 'learning_rate': 0.006543037525186631, 'num_leaves': 113, 'max_depth': 7, 'min_child_samples': 22, 'scale_pos_weight': 6.0951165210165295, 'reg_alpha': 2.185250411815612, 'reg_lambda': 0.0011091855706266162}. Best is trial 15 with value: 0.23668976345923343.

🏃 View run illustrious-bug-362 at: http://127.0.0.1:5000/#/experiments/1/runs/198dd957ac754b439d262c92c29f2af3
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

[I 2026-04-11 16:23:22,091] Trial 26 finished with value: 0.23584617160166396 and parameters: {'n_estimators': 325, 'learning_rate': 0.009680607265233935, 'num_leaves': 142, 'max_depth': 11, 'min_child_samples': 53, 'scale_pos_weight': 5.113656737879227, 'reg_alpha': 9.962157912010037, 'reg_lambda': 0.0025160088163329675}. Best is trial 15 with value: 0.23668976345923343.

🏃 View run rogue-sloth-636 at: http://127.0.0.1:5000/#/experiments/1/runs/133b50bcd5dd44f3a8286bcaa1178cd9
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

[I 2026-04-11 16:23:26,837] Trial 27 finished with value: 0.2351953569111234 and parameters: {'n_estimators': 320, 'learning_rate': 0.009611006702468282, 'num_leaves': 94, 'max_depth': 3, 'min_child_samples': 55, 'scale_pos_weight': 3.8396882147244944, 'reg_alpha': 0.022674992656007694, 'reg_lambda': 0.23621655560490282}. Best is trial 15 with value: 0.23668976345923343.

🏃 View run gentle-mouse-202 at: http://127.0.0.1:5000/#/experiments/1/runs/bc4296bc23584855a19b6924b19f4e59
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

[I 2026-04-11 16:23:46,209] Trial 28 finished with value: 0.22989389094840174 and parameters: {'n_estimators': 383, 'learning_rate': 0.013048512394537842, 'num_leaves': 127, 'max_depth': 11, 'min_child_samples': 69, 'scale_pos_weight': 2.5164587721964278, 'reg_alpha': 0.13101060041716875, 'reg_lambda': 0.0027624349407552725}. Best is trial 15 with value: 0.23668976345923343.

🏃 View run spiffy-lynx-786 at: http://127.0.0.1:5000/#/experiments/1/runs/7e9eae561fa446c2a5f971c9c503f740
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

[I 2026-04-11 16:24:08,355] Trial 29 finished with value: 0.2154916718306073 and parameters: {'n_estimators': 429, 'learning_rate': 0.054463376640602405, 'num_leaves': 140, 'max_depth': 10, 'min_child_samples': 84, 'scale_pos_weight': 3.292109240383118, 'reg_alpha': 0.009186043336641653, 'reg_lambda': 0.0073232695187137355}. Best is trial 15 with value: 0.23668976345923343.

🏃 View run smiling-kite-206 at: http://127.0.0.1:5000/#/experiments/1/runs/9a3caf04854d41a7a7fe2a3ee6d741f1
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

[I 2026-04-11 16:24:18,180] Trial 30 finished with value: 0.23262678471426493 and parameters: {'n_estimators': 557, 'learning_rate': 0.007840896723614673, 'num_leaves': 22, 'max_depth': 11, 'min_child_samples': 25, 'scale_pos_weight': 4.4971468678204305, 'reg_alpha': 0.4788219533492471, 'reg_lambda': 0.01545375580783234}. Best is trial 15 with value: 0.23668976345923343.

🏃 View run efficient-loon-366 at: http://127.0.0.1:5000/#/experiments/1/runs/cecc89f1b67b481793e2d7fdcbd81ccd
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

[I 2026-04-11 16:24:36,545] Trial 31 finished with value: 0.23684207399491886 and parameters: {'n_estimators': 324, 'learning_rate': 0.0059841790099651, 'num_leaves': 142, 'max_depth': 8, 'min_child_samples': 50, 'scale_pos_weight': 5.211301148214615, 'reg_alpha': 6.281330139299655, 'reg_lambda': 0.001958656036114767}. Best is trial 31 with value: 0.23684207399491886.

🏃 View run gentle-goose-428 at: http://127.0.0.1:5000/#/experiments/1/runs/d1ed6d5cb89946d080fdd4377d4a6412
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

[I 2026-04-11 16:24:52,175] Trial 32 finished with value: 0.23519280818230595 and parameters: {'n_estimators': 343, 'learning_rate': 0.006202199951573003, 'num_leaves': 126, 'max_depth': 8, 'min_child_samples': 51, 'scale_pos_weight': 6.429860583277093, 'reg_alpha': 1.8252372081483368, 'reg_lambda': 0.0021609119600080893}. Best is trial 31 with value: 0.23684207399491886.

🏃 View run crawling-hare-884 at: http://127.0.0.1:5000/#/experiments/1/runs/3d67d798b8aa415d98682f56bb8aa4c8
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

[I 2026-04-11 16:25:07,331] Trial 33 finished with value: 0.23613367852619466 and parameters: {'n_estimators': 459, 'learning_rate': 0.006532567692843056, 'num_leaves': 142, 'max_depth': 7, 'min_child_samples': 61, 'scale_pos_weight': 5.474885799634509, 'reg_alpha': 5.635212779494113, 'reg_lambda': 0.003971165697701417}. Best is trial 31 with value: 0.23684207399491886.

🏃 View run efficient-wren-592 at: http://127.0.0.1:5000/#/experiments/1/runs/210c721a92324ddaa7582eb945c72514
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

[I 2026-04-11 16:25:19,233] Trial 34 finished with value: 0.2363955741714879 and parameters: {'n_estimators': 458, 'learning_rate': 0.006057375512711566, 'num_leaves': 130, 'max_depth': 7, 'min_child_samples': 67, 'scale_pos_weight': 6.285313966975686, 'reg_alpha': 5.0206171624416225, 'reg_lambda': 0.036154916432250925}. Best is trial 31 with value: 0.23684207399491886.

🏃 View run carefree-pug-589 at: http://127.0.0.1:5000/#/experiments/1/runs/bf33baf2d1054927bbf0ed6995b07960
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

[I 2026-04-11 16:25:27,579] Trial 35 finished with value: 0.232197548520108 and parameters: {'n_estimators': 513, 'learning_rate': 0.02469664775600935, 'num_leaves': 131, 'max_depth': 5, 'min_child_samples': 67, 'scale_pos_weight': 7.061948568237708, 'reg_alpha': 0.975313248605186, 'reg_lambda': 0.036817436904380205}. Best is trial 31 with value: 0.23684207399491886.

🏃 View run shivering-shad-716 at: http://127.0.0.1:5000/#/experiments/1/runs/d39d9bdb6d9943018a96f1f3dfa70ff4
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

[I 2026-04-11 16:25:38,757] Trial 36 finished with value: 0.23580219139587785 and parameters: {'n_estimators': 373, 'learning_rate': 0.007900177627367538, 'num_leaves': 115, 'max_depth': 7, 'min_child_samples': 59, 'scale_pos_weight': 6.501117581675246, 'reg_alpha': 0.70420080304579, 'reg_lambda': 0.23779194197017292}. Best is trial 31 with value: 0.23684207399491886.

🏃 View run aged-hare-683 at: http://127.0.0.1:5000/#/experiments/1/runs/6a26f45df5864f69943ad6118a5911dd
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

[I 2026-04-11 16:25:48,180] Trial 37 finished with value: 0.23637944215376117 and parameters: {'n_estimators': 422, 'learning_rate': 0.0060739363291809605, 'num_leaves': 120, 'max_depth': 6, 'min_child_samples': 81, 'scale_pos_weight': 6.785884488945639, 'reg_alpha': 2.4114487490708516, 'reg_lambda': 0.11879258820195793}. Best is trial 31 with value: 0.23684207399491886.

🏃 View run adaptable-ant-872 at: http://127.0.0.1:5000/#/experiments/1/runs/400cdd15fb90437dbed88d0845fa1861
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

[I 2026-04-11 16:26:04,531] Trial 38 finished with value: 0.2320760767211238 and parameters: {'n_estimators': 645, 'learning_rate': 0.011119077829586736, 'num_leaves': 70, 'max_depth': 8, 'min_child_samples': 75, 'scale_pos_weight': 5.85167521886227, 'reg_alpha': 1.0516914025291502, 'reg_lambda': 7.60352621235415}. Best is trial 31 with value: 0.23684207399491886.

🏃 View run zealous-skunk-633 at: http://127.0.0.1:5000/#/experiments/1/runs/c644431076de46fab2c79342b156505c
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

[I 2026-04-11 16:26:27,510] Trial 39 finished with value: 0.23508813674752846 and parameters: {'n_estimators': 569, 'learning_rate': 0.008362562183233736, 'num_leaves': 131, 'max_depth': 9, 'min_child_samples': 66, 'scale_pos_weight': 6.1758539084290245, 'reg_alpha': 4.888499736423095, 'reg_lambda': 0.6473215133853341}. Best is trial 31 with value: 0.23684207399491886.

🏃 View run adorable-calf-535 at: http://127.0.0.1:5000/#/experiments/1/runs/80b53933970c40978a58c305639b5481
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

[I 2026-04-11 16:26:39,032] Trial 40 finished with value: 0.23162755201789464 and parameters: {'n_estimators': 513, 'learning_rate': 0.016316826997527692, 'num_leaves': 120, 'max_depth': 6, 'min_child_samples': 100, 'scale_pos_weight': 4.801189685123025, 'reg_alpha': 2.641327799679742, 'reg_lambda': 0.015128509942757426}. Best is trial 31 with value: 0.23684207399491886.

🏃 View run redolent-auk-863 at: http://127.0.0.1:5000/#/experiments/1/runs/86cd8296f62a437c95fca6df26d74850
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

[I 2026-04-11 16:26:48,017] Trial 41 finished with value: 0.23662170681290412 and parameters: {'n_estimators': 423, 'learning_rate': 0.005956445723959502, 'num_leaves': 121, 'max_depth': 5, 'min_child_samples': 85, 'scale_pos_weight': 6.832350038736009, 'reg_alpha': 1.5259879786779735, 'reg_lambda': 0.18066086572431672}. Best is trial 31 with value: 0.23684207399491886.

🏃 View run ambitious-lynx-253 at: http://127.0.0.1:5000/#/experiments/1/runs/a91f52f6962f4072bd02860155f3ae45
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

[I 2026-04-11 16:26:54,916] Trial 42 finished with value: 0.23580976434514594 and parameters: {'n_estimators': 459, 'learning_rate': 0.0056471447773214735, 'num_leaves': 126, 'max_depth': 5, 'min_child_samples': 90, 'scale_pos_weight': 6.737415306669641, 'reg_alpha': 1.5544609910209264, 'reg_lambda': 0.1707200190649948}. Best is trial 31 with value: 0.23684207399491886.

🏃 View run clumsy-newt-869 at: http://127.0.0.1:5000/#/experiments/1/runs/6fdc3fa1ca18499f8f2e7ec15ae0203f
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

[I 2026-04-11 16:27:00,170] Trial 43 finished with value: 0.23545995415916673 and parameters: {'n_estimators': 374, 'learning_rate': 0.005014030582734917, 'num_leaves': 112, 'max_depth': 4, 'min_child_samples': 90, 'scale_pos_weight': 7.2056957753425355, 'reg_alpha': 6.696170579879306, 'reg_lambda': 0.41097382638251195}. Best is trial 31 with value: 0.23684207399491886.

🏃 View run nimble-skunk-649 at: http://127.0.0.1:5000/#/experiments/1/runs/5a2afcaf02244beeabceb36f084db86e
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

[I 2026-04-11 16:27:04,326] Trial 44 finished with value: 0.23521986835348935 and parameters: {'n_estimators': 483, 'learning_rate': 0.007119951499195971, 'num_leaves': 144, 'max_depth': 3, 'min_child_samples': 78, 'scale_pos_weight': 6.0946147422154295, 'reg_alpha': 0.6386746885305531, 'reg_lambda': 0.0583762368742217}. Best is trial 31 with value: 0.23684207399491886.

🏃 View run tasteful-fly-111 at: http://127.0.0.1:5000/#/experiments/1/runs/eb270677eee54aa8944d2ec82b9a86bc
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

[I 2026-04-11 16:27:14,918] Trial 45 finished with value: 0.2349164021371215 and parameters: {'n_estimators': 1110, 'learning_rate': 0.006012360885390036, 'num_leaves': 134, 'max_depth': 4, 'min_child_samples': 70, 'scale_pos_weight': 6.738811876611426, 'reg_alpha': 1.1764696897221099, 'reg_lambda': 1.1130583742565665}. Best is trial 31 with value: 0.23684207399491886.

🏃 View run nosy-carp-275 at: http://127.0.0.1:5000/#/experiments/1/runs/7f78f1c647e7429ea261d379d01e5cb7
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

[I 2026-04-11 16:27:21,945] Trial 46 finished with value: 0.23173058945258843 and parameters: {'n_estimators': 361, 'learning_rate': 0.026253974630196228, 'num_leaves': 47, 'max_depth': 7, 'min_child_samples': 57, 'scale_pos_weight': 1.0084857103467124, 'reg_alpha': 4.2023512861755945, 'reg_lambda': 0.09595245618818214}. Best is trial 31 with value: 0.23684207399491886.

🏃 View run hilarious-skunk-265 at: http://127.0.0.1:5000/#/experiments/1/runs/1a7033dc134f4702b5ddd4c89b08670d
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

[I 2026-04-11 16:27:28,400] Trial 47 finished with value: 0.23755670775745005 and parameters: {'n_estimators': 415, 'learning_rate': 0.0057493843171183955, 'num_leaves': 118, 'max_depth': 5, 'min_child_samples': 63, 'scale_pos_weight': 5.4472360473324875, 'reg_alpha': 2.9175318036565674, 'reg_lambda': 2.7253620635345914}. Best is trial 47 with value: 0.23755670775745005.

🏃 View run casual-wolf-329 at: http://127.0.0.1:5000/#/experiments/1/runs/158d8e8766664828b8c10e7605836d5e
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

[I 2026-04-11 16:27:34,897] Trial 48 finished with value: 0.2307801189980594 and parameters: {'n_estimators': 417, 'learning_rate': 0.041371247579004365, 'num_leaves': 105, 'max_depth': 5, 'min_child_samples': 50, 'scale_pos_weight': 5.502546059430256, 'reg_alpha': 1.827134485142894, 'reg_lambda': 3.3531583439513115}. Best is trial 47 with value: 0.23755670775745005.

🏃 View run dashing-bird-571 at: http://127.0.0.1:5000/#/experiments/1/runs/573fd3f19d744cb5b723f0d165e9300a
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

[I 2026-04-11 16:27:44,322] Trial 49 finished with value: 0.2180573696872004 and parameters: {'n_estimators': 533, 'learning_rate': 0.09488323732793731, 'num_leaves': 124, 'max_depth': 6, 'min_child_samples': 62, 'scale_pos_weight': 5.735630917477187, 'reg_alpha': 6.662070082391561, 'reg_lambda': 1.7280680355859352}. Best is trial 47 with value: 0.23755670775745005.

🏃 View run gregarious-fox-63 at: http://127.0.0.1:5000/#/experiments/1/runs/d1971a022b9347ffbc8974f3c01ca67b
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

2026/04/11 16:27:46 WARNING mlflow.lightgbm: Saving the models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html

----------------------------------------
LightGBM tuning completed!
Best CV PR-AUC: 0.2376
Test PR-AUC: 0.2326
Best Parameters: {'n_estimators': 415, 'learning_rate': 0.0057493843171183955, 'num_leaves': 118, 'max_depth': 5, 'min_child_samples': 63, 'scale_pos_weight': 5.4472360473324875, 'reg_alpha': 2.9175318036565674, 'reg_lambda': 2.7253620635345914}
🏃 View run LGBM_PR_AUC_Optimization_CV at: http://127.0.0.1:5000/#/experiments/1/runs/9ef318856924403dbfed4624cbfeaa65
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

### Catboost

In [ ]:
# =========================================
# CatBoost tuning with CV
# =========================================
def objective_catboost(trial):
    """
    Tune CatBoost using cross-validated PR-AUC on the training set only.
    This avoids test leakage during hyperparameter search.
    """
    params = {
        "iterations": trial.suggest_int("iterations", 200, 1000),
        "depth": trial.suggest_int("depth", 4, 10),
        "learning_rate": trial.suggest_float("learning_rate", 0.01, 0.2, log=True),
        "l2_leaf_reg": trial.suggest_float("l2_leaf_reg", 1.0, 10.0),
        "subsample": trial.suggest_float("subsample", 0.5, 1.0),
        "random_strength": trial.suggest_float("random_strength", 0.0, 5.0),
        "scale_pos_weight": trial.suggest_float("scale_pos_weight", 1.0, ratio * 1.5),
        "random_state": RANDOM_STATE,
        "loss_function": "Logloss",
        "eval_metric": "PRAUC",
        "verbose": 0,
        "allow_writing_files": False,   #####
        "train_dir": str(Path("../artifacts/tmp/catboost_info"))
    }

    model = CatBoostClassifier(**params)

    # Out-of-fold predicted probabilities on training data
    y_proba_oof = cross_val_predict(
        estimator=model,
        X=X_train,
        y=y_train,
        cv=cv,
        method="predict_proba",
    )[:, 1]

    # Default classification threshold for reporting auxiliary metrics
    y_pred_oof = (y_proba_oof >= 0.5).astype(int)

    metrics = {
        "cv_pr_auc": float(average_precision_score(y_train, y_proba_oof)),
        "cv_roc_auc": float(roc_auc_score(y_train, y_proba_oof)),
        "cv_log_loss": float(log_loss(y_train, y_proba_oof)),
        "cv_accuracy": float(accuracy_score(y_train, y_pred_oof)),
        "cv_precision": float(precision_score(y_train, y_pred_oof, zero_division=0)),
        "cv_recall": float(recall_score(y_train, y_pred_oof, zero_division=0)),
        "cv_f1_score": float(f1_score(y_train, y_pred_oof, zero_division=0)),
    }

    # Log each Optuna trial as a nested MLflow run
    with mlflow.start_run(nested=True):
        mlflow.log_params(params)
        mlflow.log_metrics(metrics)

    return metrics["cv_pr_auc"]


with mlflow.start_run(run_name="CatBoost_PR_AUC_Optimization_CV"):
    logger.info("Starting CatBoost hyperparameter tuning with Stratified CV...")

    study_catboost = optuna.create_study(direction="maximize")
    study_catboost.optimize(objective_catboost, n_trials=30)

    # Log best CV result
    mlflow.log_params(study_catboost.best_params)
    mlflow.log_metric("best_cv_pr_auc", float(study_catboost.best_value))

    # Train final CatBoost model on full training set with best params
    best_catboost = CatBoostClassifier(
        **study_catboost.best_params,
        random_state=RANDOM_STATE,
        loss_function="Logloss",
        eval_metric="PRAUC",
        verbose=0,
        allow_writing_files=False,
    )
    best_catboost.fit(X_train, y_train)

    # Final evaluation on untouched test set
    y_test_proba = best_catboost.predict_proba(X_test)[:, 1]
    y_test_pred = (y_test_proba >= 0.5).astype(int)

    test_metrics = {
        "test_pr_auc": float(average_precision_score(y_test, y_test_proba)),
        "test_roc_auc": float(roc_auc_score(y_test, y_test_proba)),
        "test_log_loss": float(log_loss(y_test, y_test_proba)),
        "test_accuracy": float(accuracy_score(y_test, y_test_pred)),
        "test_precision": float(precision_score(y_test, y_test_pred, zero_division=0)),
        "test_recall": float(recall_score(y_test, y_test_pred, zero_division=0)),
        "test_f1_score": float(f1_score(y_test, y_test_pred, zero_division=0)),
    }

    mlflow.log_metrics(test_metrics)
    mlflow.sklearn.log_model(best_catboost, name="best_catboost_prauc_model")

    overall_results["CatBoost"] = {
        "model": best_catboost,
        "cv_pr_auc": float(study_catboost.best_value),
        "test_pr_auc": float(test_metrics["test_pr_auc"]),
        "params": study_catboost.best_params,
    }

    print("-" * 40)
    print("CatBoost tuning completed!")
    print(f"Best CV PR-AUC: {study_catboost.best_value:.4f}")
    print(f"Test PR-AUC: {test_metrics['test_pr_auc']:.4f}")
    print(f"Best Parameters: {study_catboost.best_params}")

2026-04-11 16:40:20 [INFO] Starting CatBoost hyperparameter tuning with Stratified CV...
[I 2026-04-11 16:40:20,950] A new study created in memory with name: no-name-69d6d53d-610b-4b4f-a695-2937d12bbfd1
[I 2026-04-11 16:41:24,784] Trial 0 finished with value: 0.21973265901210937 and parameters: {'iterations': 698, 'depth': 7, 'learning_rate': 0.09141125011342928, 'l2_leaf_reg': 8.278237754362989, 'subsample': 0.9275477415734181, 'random_strength': 1.4579462851515002, 'scale_pos_weight': 2.036926994296398}. Best is trial 0 with value: 0.21973265901210937.

🏃 View run funny-squid-626 at: http://127.0.0.1:5000/#/experiments/1/runs/a7bee7b5b49049688e89cecd2782d4a1
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

[I 2026-04-11 16:42:10,878] Trial 1 finished with value: 0.230854765500619 and parameters: {'iterations': 631, 'depth': 5, 'learning_rate': 0.06697946186303694, 'l2_leaf_reg': 3.8012222917645992, 'subsample': 0.9507105187964047, 'random_strength': 0.28871532598264305, 'scale_pos_weight': 2.353755671398708}. Best is trial 1 with value: 0.230854765500619.

🏃 View run worried-snail-34 at: http://127.0.0.1:5000/#/experiments/1/runs/55dc0a04ae4a49f1831e1f8eb76130a5
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

[I 2026-04-11 16:42:46,155] Trial 2 finished with value: 0.23169144792346424 and parameters: {'iterations': 541, 'depth': 4, 'learning_rate': 0.10025323284144673, 'l2_leaf_reg': 7.335234952019772, 'subsample': 0.929769607466133, 'random_strength': 0.19340205257376009, 'scale_pos_weight': 4.955388698044528}. Best is trial 2 with value: 0.23169144792346424.

🏃 View run salty-conch-48 at: http://127.0.0.1:5000/#/experiments/1/runs/aecf19f6685840e8a4aa68bee3ee9e42
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

[I 2026-04-11 16:43:05,910] Trial 3 finished with value: 0.23418949743111933 and parameters: {'iterations': 305, 'depth': 4, 'learning_rate': 0.05213228923879155, 'l2_leaf_reg': 9.366312522543645, 'subsample': 0.7776315834598537, 'random_strength': 2.1565537413305287, 'scale_pos_weight': 1.7985971496229216}. Best is trial 3 with value: 0.23418949743111933.

🏃 View run invincible-bee-90 at: http://127.0.0.1:5000/#/experiments/1/runs/c450cbf6dc06477fa69e2b615e0c8dfe
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

[I 2026-04-11 16:43:34,896] Trial 4 finished with value: 0.2199280434283117 and parameters: {'iterations': 210, 'depth': 9, 'learning_rate': 0.13944597191241023, 'l2_leaf_reg': 4.762809061370243, 'subsample': 0.5365740227002307, 'random_strength': 3.712492465365739, 'scale_pos_weight': 5.789596584725375}. Best is trial 3 with value: 0.23418949743111933.

🏃 View run mysterious-panda-352 at: http://127.0.0.1:5000/#/experiments/1/runs/4e64f6b944644515b7e1c6c7004f2725
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

[I 2026-04-11 16:44:23,254] Trial 5 finished with value: 0.23438616335563017 and parameters: {'iterations': 771, 'depth': 4, 'learning_rate': 0.01584838224434478, 'l2_leaf_reg': 9.199347393510164, 'subsample': 0.6125186772821404, 'random_strength': 0.30972906718826465, 'scale_pos_weight': 1.659597510639999}. Best is trial 5 with value: 0.23438616335563017.

🏃 View run caring-hare-64 at: http://127.0.0.1:5000/#/experiments/1/runs/b0a7a11a29544a3fb1236f5b1eb37007
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

[I 2026-04-11 16:45:09,226] Trial 6 finished with value: 0.2270098217910848 and parameters: {'iterations': 625, 'depth': 5, 'learning_rate': 0.0865324623445254, 'l2_leaf_reg': 7.975392864590699, 'subsample': 0.8967137466058069, 'random_strength': 2.3444222359376488, 'scale_pos_weight': 3.9034844822033947}. Best is trial 5 with value: 0.23438616335563017.

🏃 View run overjoyed-crane-369 at: http://127.0.0.1:5000/#/experiments/1/runs/92b5f7d3a12d4d429e82723145bbd01e
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

[I 2026-04-11 16:45:35,686] Trial 7 finished with value: 0.23336573461802773 and parameters: {'iterations': 328, 'depth': 5, 'learning_rate': 0.040988826584992755, 'l2_leaf_reg': 3.428935635360605, 'subsample': 0.8017286019123275, 'random_strength': 3.141546129909681, 'scale_pos_weight': 6.889827843644654}. Best is trial 5 with value: 0.23438616335563017.

🏃 View run valuable-snake-250 at: http://127.0.0.1:5000/#/experiments/1/runs/ef8901a1dc6045a5a4514dc53f26b6ff
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

[I 2026-04-11 16:46:16,894] Trial 8 finished with value: 0.23520909159193976 and parameters: {'iterations': 643, 'depth': 4, 'learning_rate': 0.02081520033208337, 'l2_leaf_reg': 3.0406911582224385, 'subsample': 0.8170570008609637, 'random_strength': 4.606765750256242, 'scale_pos_weight': 5.538641042768273}. Best is trial 8 with value: 0.23520909159193976.

🏃 View run polite-hare-869 at: http://127.0.0.1:5000/#/experiments/1/runs/3fe565546dfb46418fe51b70836bbd1e
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

[I 2026-04-11 16:49:38,258] Trial 9 finished with value: 0.21941739297585883 and parameters: {'iterations': 882, 'depth': 10, 'learning_rate': 0.09536304187944135, 'l2_leaf_reg': 3.894820663164653, 'subsample': 0.6628458876728783, 'random_strength': 1.2041956002488596, 'scale_pos_weight': 6.216925174291758}. Best is trial 8 with value: 0.23520909159193976.

🏃 View run bright-perch-805 at: http://127.0.0.1:5000/#/experiments/1/runs/bce9b0ff81c84e5bad71630e679e2157
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

[I 2026-04-11 16:51:30,134] Trial 10 finished with value: 0.23380853649331795 and parameters: {'iterations': 991, 'depth': 7, 'learning_rate': 0.012407628725353885, 'l2_leaf_reg': 1.2383863396136732, 'subsample': 0.6968086517492833, 'random_strength': 4.682576387684037, 'scale_pos_weight': 3.8214751275674947}. Best is trial 8 with value: 0.23520909159193976.

🏃 View run gregarious-whale-740 at: http://127.0.0.1:5000/#/experiments/1/runs/b776575f26c544e6a780d3251580a189
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

[I 2026-04-11 16:52:51,174] Trial 11 finished with value: 0.23472477979303286 and parameters: {'iterations': 775, 'depth': 7, 'learning_rate': 0.01693399588003187, 'l2_leaf_reg': 1.8148844083709306, 'subsample': 0.5658250866474538, 'random_strength': 4.956067697705276, 'scale_pos_weight': 3.036815694604311}. Best is trial 8 with value: 0.23520909159193976.

🏃 View run vaunted-yak-420 at: http://127.0.0.1:5000/#/experiments/1/runs/3c6be7056fd34097afce2a6641be6ffd
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

[I 2026-04-11 16:53:48,418] Trial 12 finished with value: 0.23454271679407662 and parameters: {'iterations': 467, 'depth': 8, 'learning_rate': 0.02260481204063372, 'l2_leaf_reg': 1.2327114291333434, 'subsample': 0.5069921005135661, 'random_strength': 4.8662632275307285, 'scale_pos_weight': 3.062240545570126}. Best is trial 8 with value: 0.23520909159193976.

🏃 View run likeable-loon-64 at: http://127.0.0.1:5000/#/experiments/1/runs/9ad90996944d4bf2a71400c76880d26d
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

[I 2026-04-11 16:55:11,252] Trial 13 finished with value: 0.23210349489064638 and parameters: {'iterations': 814, 'depth': 6, 'learning_rate': 0.025794243034182172, 'l2_leaf_reg': 2.4670374837576734, 'subsample': 0.8328713466002238, 'random_strength': 4.041202939110709, 'scale_pos_weight': 4.906223991700571}. Best is trial 8 with value: 0.23520909159193976.

🏃 View run sedate-jay-827 at: http://127.0.0.1:5000/#/experiments/1/runs/b31d772d73f8461cbe113db4496d1386
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

[I 2026-04-11 16:56:08,134] Trial 14 finished with value: 0.23314660000547188 and parameters: {'iterations': 487, 'depth': 7, 'learning_rate': 0.0279132307745081, 'l2_leaf_reg': 6.281000976945956, 'subsample': 0.5974044160223737, 'random_strength': 4.106088509686645, 'scale_pos_weight': 4.889405700358445}. Best is trial 8 with value: 0.23520909159193976.

🏃 View run ambitious-smelt-471 at: http://127.0.0.1:5000/#/experiments/1/runs/f60c99bc91b4432e85829e6279603571
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

[I 2026-04-11 16:58:25,727] Trial 15 finished with value: 0.23228343968644508 and parameters: {'iterations': 890, 'depth': 9, 'learning_rate': 0.015876106814206252, 'l2_leaf_reg': 2.4443234493630324, 'subsample': 0.7184284727431822, 'random_strength': 3.2167847480473952, 'scale_pos_weight': 1.0277693145046087}. Best is trial 8 with value: 0.23520909159193976.

🏃 View run bright-sponge-371 at: http://127.0.0.1:5000/#/experiments/1/runs/880cd98bc3124e9eb32b3c1ebe898f00
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

[I 2026-04-11 16:59:28,580] Trial 16 finished with value: 0.2337947250758986 and parameters: {'iterations': 708, 'depth': 6, 'learning_rate': 0.010012885546578875, 'l2_leaf_reg': 5.629034395073606, 'subsample': 0.8600986917402706, 'random_strength': 4.894260062841728, 'scale_pos_weight': 3.1266625500013316}. Best is trial 8 with value: 0.23520909159193976.

🏃 View run languid-carp-591 at: http://127.0.0.1:5000/#/experiments/1/runs/7ef91f2c76aa4b3cbac69b40f03fc289
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

[I 2026-04-11 17:01:26,915] Trial 17 finished with value: 0.22727101936009006 and parameters: {'iterations': 996, 'depth': 8, 'learning_rate': 0.035837703812520966, 'l2_leaf_reg': 2.389897362030867, 'subsample': 0.7366284302452656, 'random_strength': 4.238982376401196, 'scale_pos_weight': 5.735708644278046}. Best is trial 8 with value: 0.23520909159193976.

🏃 View run colorful-fowl-173 at: http://127.0.0.1:5000/#/experiments/1/runs/b12fb7657eef46c4b7695f9f99dd1572
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

[I 2026-04-11 17:02:32,835] Trial 18 finished with value: 0.23445238085000897 and parameters: {'iterations': 729, 'depth': 6, 'learning_rate': 0.019602994583670565, 'l2_leaf_reg': 4.703682728151206, 'subsample': 0.6291326138978262, 'random_strength': 3.268819795985392, 'scale_pos_weight': 2.9808816566798444}. Best is trial 8 with value: 0.23520909159193976.

🏃 View run trusting-wren-298 at: http://127.0.0.1:5000/#/experiments/1/runs/281b6034ed4242b4bcb06117ca0c8908
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

[I 2026-04-11 17:06:00,127] Trial 19 finished with value: 0.22608056017763084 and parameters: {'iterations': 837, 'depth': 10, 'learning_rate': 0.033746422331509374, 'l2_leaf_reg': 1.7555368995082508, 'subsample': 0.563941659650128, 'random_strength': 4.455535780993291, 'scale_pos_weight': 4.2664385903909885}. Best is trial 8 with value: 0.23520909159193976.

🏃 View run intrigued-mouse-986 at: http://127.0.0.1:5000/#/experiments/1/runs/35592802100544b2a20fc8905e84d73d
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

[I 2026-04-11 17:07:25,553] Trial 20 finished with value: 0.23657281921155787 and parameters: {'iterations': 574, 'depth': 8, 'learning_rate': 0.016544497681350235, 'l2_leaf_reg': 3.1274977505347126, 'subsample': 0.6712158273177455, 'random_strength': 3.526116781666511, 'scale_pos_weight': 7.164833583823765}. Best is trial 20 with value: 0.23657281921155787.

🏃 View run big-shark-155 at: http://127.0.0.1:5000/#/experiments/1/runs/d342ea7a2b5c4dc6bacb203ce1a88d91
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

[I 2026-04-11 17:08:45,420] Trial 21 finished with value: 0.2351884645112488 and parameters: {'iterations': 539, 'depth': 8, 'learning_rate': 0.016878282178173255, 'l2_leaf_reg': 3.040967821072513, 'subsample': 0.6673696430284642, 'random_strength': 3.8180074309947702, 'scale_pos_weight': 7.153903112736869}. Best is trial 20 with value: 0.23657281921155787.

🏃 View run capricious-trout-566 at: http://127.0.0.1:5000/#/experiments/1/runs/757367c5c05d4fb7a8cea3d2e2475a53
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

[I 2026-04-11 17:10:06,151] Trial 22 finished with value: 0.2359537674579137 and parameters: {'iterations': 551, 'depth': 8, 'learning_rate': 0.011403297604162935, 'l2_leaf_reg': 3.357023992757565, 'subsample': 0.672065614425823, 'random_strength': 3.5584918143414868, 'scale_pos_weight': 7.19247612289582}. Best is trial 20 with value: 0.23657281921155787.

🏃 View run sincere-trout-807 at: http://127.0.0.1:5000/#/experiments/1/runs/5a3d5b07a5204197ac711a268880b278
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

[I 2026-04-11 17:11:19,640] Trial 23 finished with value: 0.23415180427759677 and parameters: {'iterations': 399, 'depth': 9, 'learning_rate': 0.010439958742201582, 'l2_leaf_reg': 4.508556230757034, 'subsample': 0.9920403048097026, 'random_strength': 2.8095987574344616, 'scale_pos_weight': 6.440965735137803}. Best is trial 20 with value: 0.23657281921155787.

🏃 View run spiffy-crane-738 at: http://127.0.0.1:5000/#/experiments/1/runs/3ef6fb6958ba4519a09fd43697f79349
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

[I 2026-04-11 17:12:46,568] Trial 24 finished with value: 0.23530676473873666 and parameters: {'iterations': 582, 'depth': 8, 'learning_rate': 0.013057966247959846, 'l2_leaf_reg': 5.8452338708372436, 'subsample': 0.7588763391461606, 'random_strength': 3.57268612962661, 'scale_pos_weight': 6.553765698334308}. Best is trial 20 with value: 0.23657281921155787.

🏃 View run sassy-asp-276 at: http://127.0.0.1:5000/#/experiments/1/runs/4e1bac6149c141c988fa444a060b5453
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

[I 2026-04-11 17:14:08,781] Trial 25 finished with value: 0.23575862271598108 and parameters: {'iterations': 553, 'depth': 8, 'learning_rate': 0.012844756592934837, 'l2_leaf_reg': 6.159605487998225, 'subsample': 0.7688151603226043, 'random_strength': 3.4862737305057085, 'scale_pos_weight': 6.650246971191347}. Best is trial 20 with value: 0.23657281921155787.

🏃 View run funny-eel-419 at: http://127.0.0.1:5000/#/experiments/1/runs/93d1d80eba3940b0950e20b7453c7e58
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

[I 2026-04-11 17:15:28,052] Trial 26 finished with value: 0.23692242249695633 and parameters: {'iterations': 436, 'depth': 9, 'learning_rate': 0.012553386061217049, 'l2_leaf_reg': 6.513097185041718, 'subsample': 0.6750746733431446, 'random_strength': 2.760553451583119, 'scale_pos_weight': 7.204809399002687}. Best is trial 26 with value: 0.23692242249695633.

🏃 View run adventurous-jay-264 at: http://127.0.0.1:5000/#/experiments/1/runs/bb678707c8c74c3f968610e2fc55366f
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

[I 2026-04-11 17:16:42,013] Trial 27 finished with value: 0.23513367589830117 and parameters: {'iterations': 402, 'depth': 9, 'learning_rate': 0.01277308374932959, 'l2_leaf_reg': 6.8521970837808865, 'subsample': 0.674884721173768, 'random_strength': 2.734865661169259, 'scale_pos_weight': 7.094615032391042}. Best is trial 26 with value: 0.23692242249695633.

🏃 View run gaudy-horse-480 at: http://127.0.0.1:5000/#/experiments/1/runs/a5fa7a2839304317965bda8c5616968a
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

[I 2026-04-11 17:18:47,734] Trial 28 finished with value: 0.23354476751613262 and parameters: {'iterations': 461, 'depth': 10, 'learning_rate': 0.02721523629752095, 'l2_leaf_reg': 5.242909835344531, 'subsample': 0.6431130031592336, 'random_strength': 2.0150403055231045, 'scale_pos_weight': 6.079523146600465}. Best is trial 26 with value: 0.23692242249695633.

🏃 View run languid-boar-578 at: http://127.0.0.1:5000/#/experiments/1/runs/693ba061c6aa4462baeb2969ebb26925
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

[I 2026-04-11 17:20:02,675] Trial 29 finished with value: 0.23615612518454346 and parameters: {'iterations': 385, 'depth': 9, 'learning_rate': 0.010556700269666576, 'l2_leaf_reg': 7.102612825356804, 'subsample': 0.7181612761087698, 'random_strength': 2.7361589851608703, 'scale_pos_weight': 5.334539661254458}. Best is trial 26 with value: 0.23692242249695633.

🏃 View run flawless-grub-98 at: http://127.0.0.1:5000/#/experiments/1/runs/9b8d7107e6c5437a968473fc00f5423c
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

2026/04/11 17:20:20 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html

----------------------------------------
CatBoost tuning completed!
Best CV PR-AUC: 0.2369
Test PR-AUC: 0.2444
Best Parameters: {'iterations': 436, 'depth': 9, 'learning_rate': 0.012553386061217049, 'l2_leaf_reg': 6.513097185041718, 'subsample': 0.6750746733431446, 'random_strength': 2.760553451583119, 'scale_pos_weight': 7.204809399002687}
🏃 View run CatBoost_PR_AUC_Optimization_CV at: http://127.0.0.1:5000/#/experiments/1/runs/0a26ae2c5eeb4296a23eafe799aefdee
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

In [51]:
#### Backfill additional evaluation metrics for trained models

DEFAULT_THRESHOLD = 0.5

for model_name, info in overall_results.items():
    model = info["model"]
    y_test_proba = model.predict_proba(X_test)[:, 1]
    y_test_pred = (y_test_proba >= DEFAULT_THRESHOLD).astype(int)

    info.update({
        "test_pr_auc": float(average_precision_score(y_test, y_test_proba)),
        "accuracy": float(accuracy_score(y_test, y_test_pred)),
        "precision": float(precision_score(y_test, y_test_pred, zero_division=0)),
        "recall": float(recall_score(y_test, y_test_pred, zero_division=0)),
        "f1_score": float(f1_score(y_test, y_test_pred, zero_division=0)),
        "roc_auc": float(roc_auc_score(y_test, y_test_proba)),
        "log_loss": float(log_loss(y_test, y_test_proba)),
        "predicted_positive_rate": float(y_test_pred.mean()),
        "threshold": float(DEFAULT_THRESHOLD),
    })

print("Updated overall_results with additional test metrics.")
for model_name, info in overall_results.items():
    print(
        model_name,
        "PR-AUC:", round(info["test_pr_auc"], 4),
        "| Acc:", round(info["accuracy"], 4),
        "| Prec:", round(info["precision"], 4),
        "| Rec:", round(info["recall"], 4),
        "| F1:", round(info["f1_score"], 4),
        "| ROC-AUC:", round(info["roc_auc"], 4),
        "| LogLoss:", round(info["log_loss"], 4),
        "| PPR:", round(info["predicted_positive_rate"], 4),
    )

Updated overall_results with additional test metrics.
RandomForest PR-AUC: 0.2405 | Acc: 0.6305 | Prec: 0.2544 | Rec: 0.5935 | F1: 0.3562 | ROC-AUC: 0.6395 | LogLoss: 0.6331 | PPR: 0.4017
XGBoost PR-AUC: 0.2351 | Acc: 0.8278 | Prec: 0.0 | Rec: 0.0 | F1: 0.0 | ROC-AUC: 0.6323 | LogLoss: 0.4495 | PPR: 0.0
LightGBM PR-AUC: 0.2326 | Acc: 0.6188 | Prec: 0.251 | Rec: 0.6115 | F1: 0.3559 | ROC-AUC: 0.6349 | LogLoss: 0.6531 | PPR: 0.4196
CatBoost PR-AUC: 0.2444 | Acc: 0.4142 | Prec: 0.2076 | Rec: 0.8525 | F1: 0.3339 | ROC-AUC: 0.6383 | LogLoss: 0.7648 | PPR: 0.7072
Baseline_LogisticRegression PR-AUC: 0.2373 | Acc: 0.6208 | Prec: 0.2514 | Rec: 0.608 | F1: 0.3558 | ROC-AUC: 0.6344 | LogLoss: 0.6614 | PPR: 0.4164

# Final summary and best model export

In [53]:
# =========================================
# Final summary and best model export
# =========================================

# Convert overall results to a summary table
summary_rows = []
for model_name, info in overall_results.items():
    summary_rows.append({
        "model": model_name,
        "cv_pr_auc": None if info["cv_pr_auc"] is None else float(info["cv_pr_auc"]),
        "test_pr_auc": float(info["test_pr_auc"]),
        "accuracy": float(info["accuracy"]),
        "precision": float(info["precision"]),
        "recall": float(info["recall"]),
        "f1_score": float(info["f1_score"]),
        "roc_auc": float(info["roc_auc"]),
        "log_loss": float(info["log_loss"]),
        "predicted_positive_rate": float(info["predicted_positive_rate"]),
        "threshold": float(info["threshold"]),
        "params": info["params"],
    })

results_df = pd.DataFrame(summary_rows).sort_values(
    by="test_pr_auc",
    ascending=False
).reset_index(drop=True)

print("=" * 100)
print("MODEL COMPARISON SUMMARY")
print("=" * 100)
display(
    results_df[
        [
            "model",
            "cv_pr_auc",
            "test_pr_auc",
            "accuracy",
            "precision",
            "recall",
            "f1_score",
            "roc_auc",
            "log_loss",
            "predicted_positive_rate",
            "threshold",
        ]
    ]
)

# Select the current best model based on clean test PR-AUC
best_model_name = results_df.loc[0, "model"]
best_info = overall_results[best_model_name]

print("\n" + "=" * 60)
print("CURRENT WINNER")
print("=" * 60)
print(f"Best model: {best_model_name}")
print(f"Best CV PR-AUC: {best_info['cv_pr_auc']:.4f}")
print(f"Best Test PR-AUC: {best_info['test_pr_auc']:.4f}")
print(f"Best Accuracy: {best_info['accuracy']:.4f}")
print(f"Best Precision: {best_info['precision']:.4f}")
print(f"Best Recall: {best_info['recall']:.4f}")
print(f"Best F1-score: {best_info['f1_score']:.4f}")
print(f"Best ROC-AUC: {best_info['roc_auc']:.4f}")
print(f"Best Log Loss: {best_info['log_loss']:.4f}")
print(f"Predicted Positive Rate: {best_info['predicted_positive_rate']:.4f}")
print(f"Threshold: {best_info['threshold']:.2f}")
print(f"Best Parameters: {best_info['params']}")

====================================================================================================
MODEL COMPARISON SUMMARY
====================================================================================================

,model,cv_pr_auc,test_pr_auc,accuracy,precision,recall,f1_score,roc_auc,log_loss,predicted_positive_rate,threshold
0,CatBoost,0.236922,0.244381,0.4142,0.207579,0.852497,0.333864,0.638279,0.764783,0.7072,0.5
1,RandomForest,0.238763,0.240469,0.6305,0.254419,0.593496,0.356160,0.639520,0.633092,0.4017,0.5
2,Baseline_LogisticRegression,NaN,0.237302,0.6208,0.251441,0.608014,0.355759,0.634450,0.661404,0.4164,0.5
3,XGBoost,0.236567,0.235103,0.8278,0.000000,0.000000,0.000000,0.632304,0.449477,0.0000,0.5
4,LightGBM,0.237557,0.232556,0.6188,0.250953,0.611498,0.355863,0.634938,0.653060,0.4196,0.5

============================================================
CURRENT WINNER
============================================================
Best model: CatBoost
Best CV PR-AUC: 0.2369
Best Test PR-AUC: 0.2444
Best Accuracy: 0.4142
Best Precision: 0.2076
Best Recall: 0.8525
Best F1-score: 0.3339
Best ROC-AUC: 0.6383
Best Log Loss: 0.7648
Predicted Positive Rate: 0.7072
Threshold: 0.50
Best Parameters: {'iterations': 436, 'depth': 9, 'learning_rate': 0.012553386061217049, 'l2_leaf_reg': 6.513097185041718, 'subsample': 0.6750746733431446, 'random_strength': 2.760553451583119, 'scale_pos_weight': 7.204809399002687}

In [54]:
### Threshold Selection for Final Model
import numpy as np
import pandas as pd
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

# Use the selected winner model directly from overall_results
final_model = overall_results[best_model_name]["model"]

# Predict probabilities on the same clean test set
y_proba_final = final_model.predict_proba(X_test)[:, 1]

# Sweep thresholds
rows = []
thresholds = np.arange(0.10, 0.91, 0.05)

for t in thresholds:
    y_pred_final = (y_proba_final >= t).astype(int)
    rows.append({
        "threshold": round(float(t), 2),
        "accuracy": float(accuracy_score(y_test, y_pred_final)),
        "precision": float(precision_score(y_test, y_pred_final, zero_division=0)),
        "recall": float(recall_score(y_test, y_pred_final, zero_division=0)),
        "f1_score": float(f1_score(y_test, y_pred_final, zero_division=0)),
        "predicted_positive_rate": float(y_pred_final.mean()),
    })

threshold_df = pd.DataFrame(rows).sort_values(
    by="f1_score",
    ascending=False
).reset_index(drop=True)

print("=" * 100)
print(f"THRESHOLD ANALYSIS FOR FINAL MODEL: {best_model_name}")
print("=" * 100)
display(threshold_df)

====================================================================================================
THRESHOLD ANALYSIS FOR FINAL MODEL: CatBoost
====================================================================================================

,threshold,accuracy,precision,recall,f1_score,predicted_positive_rate
0,0.60,0.6289,0.254262,0.597561,0.356734,0.4047
1,0.65,0.6408,0.256129,0.570267,0.353492,0.3834
2,0.55,0.5424,0.226942,0.688734,0.341393,0.5226
3,0.50,0.4142,0.207579,0.852497,0.333864,0.7072
4,0.45,0.3861,0.204628,0.888502,0.332645,0.7477
5,0.40,0.3738,0.201943,0.893148,0.329407,0.7616
6,0.35,0.3027,0.190426,0.937863,0.316574,0.8481
7,0.30,0.2009,0.175080,0.980836,0.297124,0.9647
8,0.20,0.1723,0.172217,1.000000,0.293832,0.9999
9,0.10,0.1722,0.172200,1.000000,0.293807,1.0000
10,0.15,0.1722,0.172200,1.000000,0.293807,1.0000
11,0.25,0.1738,0.172082,0.996516,0.293484,0.9972
12,0.70,0.7731,0.252936,0.162602,0.197950,0.1107
13,0.75,0.8278,0.000000,0.000000,0.000000,0.0000
14,0.80,0.8278,0.000000,0.000000,0.000000,0.0000
15,0.85,0.8278,0.000000,0.000000,0.000000,0.0000
16,0.90,0.8278,0.000000,0.000000,0.000000,0.0000

In [55]:
## Recall-priority threshold candidates

recall_priority_df = threshold_df[threshold_df["recall"] >= 0.80].sort_values(
    by=["precision", "f1_score"],
    ascending=[False, False]
).reset_index(drop=True)

print("=" * 100)
print("THRESHOLDS WITH RECALL >= 0.80")
print("=" * 100)
display(recall_priority_df.head(10))

====================================================================================================
THRESHOLDS WITH RECALL >= 0.80
====================================================================================================

   threshold  accuracy  precision    recall  f1_score  predicted_positive_rate
0       0.50    0.4142   0.207579  0.852497  0.333864                   0.7072
1       0.45    0.3861   0.204628  0.888502  0.332645                   0.7477
2       0.40    0.3738   0.201943  0.893148  0.329407                   0.7616
3       0.35    0.3027   0.190426  0.937863  0.316574                   0.8481
4       0.30    0.2009   0.175080  0.980836  0.297124                   0.9647
5       0.20    0.1723   0.172217  1.000000  0.293832                   0.9999
6       0.10    0.1722   0.172200  1.000000  0.293807                   1.0000
7       0.15    0.1722   0.172200  1.000000  0.293807                   1.0000
8       0.25    0.1738   0.172082  0.996516  0.293484                   0.9972

In [56]:
### Select final threshold
# Final threshold decision based on business preference
chosen_threshold = 0.50

chosen_threshold_row = threshold_df[threshold_df["threshold"] == round(chosen_threshold, 2)]

print("=" * 100)
print("FINAL THRESHOLD DECISION")
print("=" * 100)
print(f"Chosen threshold: {chosen_threshold}")

if not chosen_threshold_row.empty:
    display(chosen_threshold_row)
else:
    print("Chosen threshold not found in threshold table.")

====================================================================================================
FINAL THRESHOLD DECISION
====================================================================================================
Chosen threshold: 0.5

   threshold  accuracy  precision    recall  f1_score  predicted_positive_rate
3        0.5    0.4142   0.207579  0.852497  0.333864                   0.7072

# Export final configs and reports

In [ ]:
from pathlib import Path

ARTIFACTS_DIR = Path("../artifacts/models")
REPORTS_DIR = Path("../reports")

ARTIFACTS_DIR.mkdir(parents=True, exist_ok=True)
REPORTS_DIR.mkdir(parents=True, exist_ok=True)

# Save model comparison report
comparison_df = results_df.copy().rename(columns={"model": "model_name"})
comparison_path = REPORTS_DIR / "model_comparison.csv"
comparison_df.to_csv(comparison_path, index=False)

print("\nSaved model comparison report to:")
print(comparison_path)

# Build final best model config WITH chosen threshold
best_model_config = {
    "project": "Netflix_Prediction",
    "best_model_overall": best_model_name,
    "selection_metric": "test_pr_auc",
    "threshold": float(chosen_threshold),
    "metrics": {
        "cv_pr_auc": float(best_info["cv_pr_auc"]),
        "test_pr_auc": float(best_info["test_pr_auc"]),
        "accuracy": float(best_info["accuracy"]),
        "precision": float(best_info["precision"]),
        "recall": float(best_info["recall"]),
        "f1_score": float(best_info["f1_score"]),
        "roc_auc": float(best_info["roc_auc"]),
        "log_loss": float(best_info["log_loss"]),
        "predicted_positive_rate": float(best_info["predicted_positive_rate"]),
    },
    "hyperparameters": best_info["params"],
}

best_model_config_path = ARTIFACTS_DIR / "best_model_config.yaml"
with open(best_model_config_path, "w", encoding="utf-8") as f:
    yaml.dump(best_model_config, f, default_flow_style=False, sort_keys=False)

print("\nSaved best model config to:")
print(best_model_config_path)


###
baseline_model_name = "Baseline_LogisticRegression"
baseline_info = overall_results[baseline_model_name]

baseline_config = {
    "project": "Netflix_Prediction",
    "model_name": baseline_model_name,
    "selection_metric": "test_pr_auc",
    "threshold": float(baseline_info.get("threshold", 0.5)),
    "metrics": {
        "cv_pr_auc": None if baseline_info["cv_pr_auc"] is None else float(baseline_info["cv_pr_auc"]),
        "test_pr_auc": float(baseline_info["test_pr_auc"]),
        "accuracy": float(baseline_info["accuracy"]),
        "precision": float(baseline_info["precision"]),
        "recall": float(baseline_info["recall"]),
        "f1_score": float(baseline_info["f1_score"]),
        "roc_auc": float(baseline_info["roc_auc"]),
        "log_loss": float(baseline_info["log_loss"]),
        "predicted_positive_rate": float(baseline_info["predicted_positive_rate"]),
    },
    "hyperparameters": baseline_info["params"],
}

baseline_config_path = ARTIFACTS_DIR / "baseline_model_config.yaml"
with open(baseline_config_path, "w", encoding="utf-8") as f:
    yaml.dump(baseline_config, f, default_flow_style=False, sort_keys=False)

print("\nSaved baseline model config to:")
print(baseline_config_path)

Saved model comparison report to:
..\reports\model_comparison.csv

Saved best model config to:
..\artifacts\models\best_model_config.yaml

Saved baseline model config to:
..\artifacts\models\baseline_model_config.yaml